### ISSUE TITLE
[Bug] Workplace chat does not trigger notifications

### ISSUE THREAD

**Issue by aberonni** [meetfranz/franz#1029]
### Expected Behavior
When I receive a message on Workplace, I should receive a notification and the badge icon should be updated accordingly.

### Current Behavior
When I receive a message on Workplace, I do not receive a notification and the badge icon does not change.

### Steps to Reproduce
1. Sign into Franz with a Workplace account
2. Minimize Franz
3. Ask someone to send you a message
4. Observe

### Your Environment
* Franz Version used: 5.0.0-beta.18 (5.0.0-beta.18.903)
* Operating System and version: Macbook Pro - MacOS Sierra 10.13.6 (17G65)

**Comment by Wouter0100** [comment]
By any chance, isn't there an option in Workplace to enable notifications? If not, it may also be useful to open an issue [here](https://github.com/edm00se/franz-recipe-watson-workspace/issues).

**Comment by aberonni** [comment]
@Wouter0100 the notifications are enabled and they work fine on the Workplace desktop and mobile apps. Also, the above link opens the Workspace integration for IBM.

**Comment by Wouter0100** [comment]
@aberonni sorry! I see, this issue seems already fixed - but the recipes in Franz are lacking behind in updates. See [this](https://github.com/rherwig/franz-5-workplace) repository. It has been updated some days back with [this](https://github.com/rherwig/franz-5-workplace/commit/c24a29e726f5d573606f409b651abd8eb09c6795) fix. See [here](https://github.com/meetfranz/plugins/blob/master/docs/integration.md#user-content-installation) how to manually install a recipe from git, which will overwrite the ones from the centralised Franz repository.

**Comment by aberonni** [comment]
@Wouter0100 thanks for getting back to me! Will close this issue now and try and install the recipe from git. Much appreciated!

**Comment by aberonni** [comment]
For those still encountering the issue, it seems that the bug is still not entirely fixed. I have submitted a [PR with the fix](https://github.com/rherwig/franz-5-workplace/pull/5)

**Comment by closingin** [comment]
Hello @rherwig ,

I think you didn't merge the correct PR (even though the merged one was also necessary) as I see it still opened. The one you merged comes from #1206 ! :slightly_smiling_face: 

Thanks for maintaining it !
