### ISSUE TITLE
Not responding to mousewheel after PC start

### ISSUE THREAD

**Issue by fabiandecuveland** [meetfranz/franz#1033]
### Expected Behavior

The messengers chat areas should be scrollable via mousewheel.

### Current Behavior

The chat areas don't respond to the mousewheel. Only after manually reloading each service, it works again.

### Steps to Reproduce (for bugs)

1. Have Franz installed with some messenger services, reboot PC
2. Franz autostarts and chats can't be scrolled

### Your Environment

* Franz Version used: 5.0.0-beta.18 Release 1.8.4
* Operating System and version: Win10 Pro 1803, 64 bit

**Comment by tjyrkinen** [comment]
Good call that this relates to start up. Suffering from the same problem but the problem seems to not exist if I exit Franz and start it again manually.

Not sure if the problematic behavior is the same with you - for me there is a small scrollable area on the left side (almost to the edge) of each scrollable window, most of them / most of the time the scrollable area overflowing on top the next element to the left. For example on Discord I could scroll the main chat area window by moving the cursor over the channel list and then scrolling with the wheel. Even then the scrolling doesn't feel quite responsive enough.

**Comment by fabiandecuveland** [comment]
The issue got worse, it now appears not only after restarting.
