### ISSUE TITLE
notifications toggle always disabled on launch and 'File->Quit' is not working

### ISSUE THREAD

**Issue by D33pTh0ught** [meetfranz/franz#1037]
- Franz does not remember the setting of the notification toggle from the previous session. Notifications & audio is always disabled when I launch the application.

- The 'File->Quit' entry in the menu does nothing. The 'Quit Franz' entry in the context menu of the system tray icon works without issue.

The issues are consistent across three different Windows 10 devices.

**Comment by thomasgustavo** [comment]
I second the notification issue. Every time I open Franz, I have to click the bell icon to enable notifications. Too bad this issue is 6 months old, and is still happening on the last franz version available today (5.0.0-beta.22). Windows 10 laptop here.

The quit issue reported by @D33pTh0ught seems to be fixed.

**Comment by kdarbela** [comment]
I personally want the notifications disabled - I am having to disable the setting each time I start the application. It does not remember the setting each time.
