### ISSUE TITLE
[Linux] Audio notifications not muting

### ISSUE THREAD

**Issue by Pk13055** [meetfranz/franz#1049]
The audio pings from various services keep chiming through even after disabling them per service, or franz as a whole.

### Expected Behavior
- Should mute in either disable case

### Current Behavior
- Does not mute

### Steps to Reproduce (for bugs)
1. Open franz
2. Disable audio for the entire app
3. Notice audio still passes through
4. cry

### Your Environment
* Franz Version used: 5.0.0.0-beta-18
* Operating System and version: Linux 4.15.0-29-generic #31-Ubuntu SMP x86_64 GNU/Linux
(Ubuntu 18.04)

**Comment by martinhellwagner** [comment]
Same for macOS 10.13.6 and Franz 5.0.0-beta18.

**Comment by martinhellwagner** [comment]
Same for macOS 10.13.6 and Franz 5.0.0-beta18.

**Comment by ulgens** [comment]
Same for `4.17.14-arch1-1-ARCH` - KDE.

**Comment by botboteverywhere** [comment]
Same here on macOS 10.12.6 and Version 5.0.0-beta.18 (5.0.0-beta.18.903) 😢

Any update on this please?

**Comment by martinhellwagner** [comment]
Strangely, it worked for me when I logged out, closed Franz, opened it and logged in again. 🤔 
However, I don't think there's any development on Franz any time soon.

**Comment by adictn** [comment]
Same for me, Windows 10 / v5.0.0-beta.19 / release 2.0.13
Also, the red notification badge in taskbar stopped showing for no reason.

Is this project still alive?

**Comment by francwalter** [comment]
Still unfixed.

**Comment by Mojo90** [comment]
+1

that is really bugging since a long time and just want to report it. But there are enough Bugs open to it. For me it is not working for WhatsApp and Telegram but for Slack thank god it is muted. But what I really don't understand is that I also did mute the sound of Franz in the Apple Notifications settings (see image) and still the sound is always there? Isn't this also an Apple bug or how would that work?

<img width="662" alt="screenshot 2019-02-03 11 32 46" src="https://user-images.githubusercontent.com/2122156/52175700-0f86eb00-27a8-11e9-9045-ed937d0c6ceb.png">

**Comment by francwalter** [comment]
The annoying audio is partly fixed in 5.0.0 Beta 23, that means now there are not anymore any audio alert :)
This is still buggy, but I don't complain with that way, much, much better than before with unwanted audio alerts all the time ;)
Thanks.

**Comment by francwalter** [comment]
In 5.0.0 beta24 the sound alert is working 👍

**Comment by Mojo90** [comment]
yes you are right 🙏🏿 also fix for macOS 10.14.2
