### ISSUE TITLE
Memory leak: >8gb of ram usage

### ISSUE THREAD

**Issue by lapauwThomas** [meetfranz/franz#1070]
### Expected Behavior

Not using 8 GB of ram
### Current Behavior

After being open for a long time. e.g When getting back to the office in the morning, franz is using more than 8Gb of ram
### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/18445742/45142317-85b30180-b1b8-11e8-8d3b-525766a3e437.png)

### Steps to Reproduce (for bugs)

Not really found a method to reproduce this, except for leaving my pc running for a long time. Only happens occasionally. I will try to narrow it down to see whether it is a service causing this or not.

### Your Environment

* Franz Version used: 
![image](https://user-images.githubusercontent.com/18445742/45142386-b1ce8280-b1b8-11e8-83ce-31a9de26129c.png)

Using the following services: Whatsapp, facebook messenger, slack x2, google calendar, google keep, Outlook, pushbullet

* Operating System and version:
W10

**Comment by devZer0** [comment]
why do you automatically close tickets from users who report a memory leak just because nobdy respnded ?  i was contacted by a collueague because he has problems with his macbook and he found franz app using 2,5gb of memory.  a little bit much for a chat app, will recommend using something other...

**Comment by lodi-g** [comment]
Found out Franz is using on average 3GB of my RAM.
Bye bye Franz.

**Comment by stefahn** [comment]
@adlk : Are you aware of the issue? Can this be fixed someday?

My Franz has about 1 GB of RAM, which is quite much too. It has this high memory usage already after running for one day.

**Comment by e-d** [comment]
Haha, you guys are complaining about a few GB or RAM usage? The past couple of days I've left my PC on overnight I come back to Franz using about 20 GB of RAM. I've disabled all my services to see if it is one of the services I'm connecting to, but it continues to use all my PC's available memory so that everything runs sluggish until I kill Franz.

I didn't notice the issue before, but the past 3 days it has sucked up all my memory running overnight. I'm on Version: 5.0.0 Release: 4.0.4 / win 32 / x64

**Comment by devZer0** [comment]
i complained  because it smells like a memory leak - and you confirm that apparently it IS one
