### ISSUE TITLE
Android port?

### ISSUE THREAD

**Issue by erotavlas85** [meetfranz/franz#1080]
It would be very useful to have an all in one messenger on android.

**Comment by erotavlas85** [comment]
There is already a similar app [disa](http://disa.im/).

**Comment by erotavlas85** [comment]
What about using [native script](https://www.nativescript.org/)?

**Comment by indykoning** [comment]
Things like this aren't fully out of the question, however using Nativescript would mean that the whole Franz application would have to be built from scratch and the plugins that are currently working for the desktop applications wouldn't work on the apps.

The nice thing about Electron is that it works on Linux, Windows and Mac without the need to change any code. And you only really need to know JS, CSS and HTML to get started. However Electron isn't available for android yet, this mainly is because NodeJS (Where Franz and Electron run on) isn't very stable on android yet so Electron is holding off development for android releases if they plan on building it.

I really do hope that at some point everything falls into place and Franz could be made to work on android.

**Comment by erotavlas85** [comment]
Thank you for the detailed answer.
NodeJS it is build on top of V8 managed by google. It is curious that NodeJS does not work on android managed by google.
