### ISSUE TITLE
Slack not conencting

### ISSUE THREAD

**Issue by Que88** [meetfranz/franz#1108]
I have two slack accounts, one of them is connecting, the other now.
I tried refresh, remove/re-add but it does not work.

I have the latest version of Franz on Win 10.

**Comment by riptide-dev** [comment]
@Que88 - Can you please provide some additional information, and I will try to repro:







### Expected Behavior



### Current Behavior



### Screenshots (if appropriate):

### Possible Solution



### Steps to Reproduce (for bugs)


1.
2.
3.
4.

### Context



### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by Que88** [comment]
It resolved itself about 1 hour later, thanks.

**Comment by riptide-dev** [comment]
@Que88 - Good to hear!
