### ISSUE TITLE
Add a PPA for Ubuntu!

### ISSUE THREAD

**Issue by jasmines** [meetfranz/franz#1149]
I'd like to buy the enterprise version, but I would need Ubuntu PPA or snap via snap official repositories.
Thank you.

**Comment by adlk** [comment]
Please specify the use case that qualifies that feature request.

**Comment by krisives** [comment]
@adlk I think it's so that users who can't follow the build instructions can use the software, which is understandable.

I believe that it could be packaged and put into Launchpad by automating those build steps such as `npm run build`

Is there listed anywhere the version of NodejS required to run this? I know that many different distros vary a lot in which version they have in their repos.

**Comment by adlk** [comment]
Please pardon my ignorance but Franz is already distributed as a .deb and .AppImage package as an tar.gz (unpacked). It is _not_ necessary to build Franz (for most of the Linux platforms) in order to run the app. 

Please understand that I'm not going to support all of the available linux packages just because they exist as every package adds more and more overhead to get new releases out.

I'm happy to hear out all arguments for PPA but at this point, I don't see a major benefit over .deb and AppImage.

> Is there listed anywhere the version of NodejS required to run this? I know that many different distros vary a lot in which version they have in their repos.

There is the .nvmr that defines the node version that should be used:
https://github.com/meetfranz/franz/blob/43fdc7a6f47d6a4997b0d827309a37e2d6b6fe35/.nvmrc#L1

**Comment by krisives** [comment]
> It is not necessary to build Franz

Correct, but it's required that users constantly check for new versions of the software and install .deb files manually.

Thanks for show me where the nodejs versions are for this.

I understand it's a hassle to support many different downstream packagers. Can you at least point us in the direction of where the `debian/control` files for source are right now for building the existing `.deb` files so this process can be automated on Launchpad?

**Comment by sverhagen** [comment]
There may not be `debian/control` files in the repository, they seem to be just generated on the fly by `electron-builder` (due to [this](https://github.com/meetfranz/franz/commit/fd86dd7079b1491a6c8f0e62f817b4a235d6ab31)).

The lack of auto-updating that comes with the `.deb` files is just unfortunate. I wonder how that looks for the AppImage versions?

**Comment by Xerus2000** [comment]
AppImages are just standalone executable files, they should only be the last resort.

Most messaging applications (Discord, Slack) now have a snap package, because you support many distros at once that way, and it enables updating via the command line as well, so that could be an attractive option.

**Comment by spyrosn** [comment]
+1 for the PPA please, auto updates are a big plus for casual users, and I'm sure that this will expand your user base.

Btw thanks for this application, this has been working flawlessly for me the past few months (up to the point that Slack stopped supporting the older version I have).

**Comment by hcNick** [comment]
+1 for PPA

**Comment by ntorga** [comment]
+1 for PPA or Snap, updating manually is just sad.

**Comment by eqagunn** [comment]
+1 for PPA or Snap in order to automate updates.

**Comment by CodeLionX** [comment]
+1 for PPA or Snap to help automatically update the Franz installation.

**Comment by Xerus2000** [comment]
Please stop commenting +1 in respect to the people who want to hear about actual updates. Instead, upvote the request directly.

**Comment by PSBaffins** [comment]
A ppa would allow Franz to be installed on Ubuntu Touch devices far more easily through Libertine

**Comment by rokonxr** [comment]
@adlk You may don't know enough about snap packages... http://snapcraft.io/
It's a universal package format, meaning you don't have to support...
> **all of the available linux packages just because they exist**

Auto update + delta updates are killer snap feature for franz...

**Comment by kewi69** [comment]
Find it strange to oppose the concept of uploading this package to some repository, either debian or rpm. But it probably is primarily focused on windows ppl. Who are used to manually have to check for updates, without considering security updates.
That disrespect of your users are sad. Re-installed my laptop recently. Liked Franz, but won't be installed again.

**Comment by dpinol** [comment]
come on, it's a pain to have to upgrade manually

**Comment by spyrosn** [comment]
You know what, I don't even care any more... Slack integration is broken since forever and I've uninstalled the app since. A pity, really. It was good for a time. -------- Αρχικό μήνυμα --------Από: Daniel Pinyol <notifications@github.com>Ημερομηνία: Σάβ, 16 Ιαν 2021, 13:19Προς: meetfranz/franz <franz@noreply.github.com>Κοιν.: spyrosn <spyrosn2006@gmail.com>, Comment <comment@noreply.github.com>Θέμα: Re: [meetfranz/franz] Add a PPA for Ubuntu! (#1149)
come on, it's a pain to have to upgrade manually

**Comment by MatteoGalet** [comment]
I created a local repo on my server and added latest franz version.
Feel free to add it to your sources.list!
I update it as frequently as possible, I will implement an auto'updater in the next future.

`wget -qO - http://home.gltmtt.com/repo/conf/apt/repo-key.gpg | sudo apt-key add -
`sudo add-apt-repository 'deb http://home.gltmtt.com/repo all main'
