### ISSUE TITLE
Whatsapp is glitchy af 

### ISSUE THREAD

**Issue by arjunkalburgi** [meetfranz/franz#1158]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8989414/49598041-65bfe500-f943-11e8-93e6-a39d2f5879da.png)
constantly having this and they move around I can't read anything 

**To Reproduce**
1. Go to Whatsapp

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Version 5.0.0-beta

**Comment by askalburgi** [comment]
Not just whatsapp, Franz itself is glitchy 
![image](https://user-images.githubusercontent.com/8989414/49598202-bdf6e700-f943-11e8-832c-5232a34365dd.png)

**Comment by adlk** [comment]
Please specify your macOS version. 

Have you tried to disable GPU acceleration in settings?

**Comment by lwiml** [comment]
> Please specify your macOS version.
> 
> Have you tried to disable GPU acceleration in settings?

For me it's just freezing sometimes, but when i disabled the GPU acceleration, i got this glitching bug seen in the screenshot

Desktop:
- Version 5.0.0-beta.19 (5.0.0-beta.19.1004)
- Mac OSX 10.14.1 (18B75)

**Comment by adlk** [comment]
You might need to login to all services again but it's worth a try to quit the app, completely wipe your Franz folder in `~/Library/Application Support/Franz` and then start the app again.

**Comment by lwiml** [comment]
Thanks for the tip, but it's still freezing sometimes

**Comment by lwiml** [comment]
For the glitchy bug though, i would suggest turning ON "gpu acceleration"
@askalburgi  does that work for you?

**Comment by mike-mccormick** [comment]
I was in the issues list to see if anyone else was having performance issues, mine are most noticeable in slack.

Turning off GPU acceleration seems to have made a massive difference. Switching between conversations and rooms in slack seems to involve either a couple of seconds delay on loading, a couple of seconds before I could type, or a mixture of the two.

WhatsApp doesn't work great, but at least part of that is because WhatsApp web has always been kinda terrible.

Screendump of System:

![image](https://user-images.githubusercontent.com/2361501/50155428-ef689e80-02c3-11e9-9540-c53a9fb509ce.png)

Text details (to follow reporting format)

Desktop:

* Version 5.0.0-beta.22 (5.0.0-beta.22.1059)
* MacOS 10.14 (18A391)

Franz is installed in Applications, using the DMG provided on the website.

Ping me if there's any debug information I can provide to help.
