### ISSUE TITLE
Franz icon permanently has "new message" red dot for no reason & Discord has weird red dot

### ISSUE THREAD

**Issue by PlaceboPRS** [meetfranz/franz#1190]
**Describe the bug**
The icons of both system tray and task bar show a red dot as if there's a new message but there isn't a message waiting.

**To Reproduce**
1. launch franz
2. look at icon in system tray or taskbar or Discord icon inside Franz

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/23120453/50106249-9ea76600-022f-11e9-9bcd-b03e649c98fd.png)
![image](https://user-images.githubusercontent.com/23120453/50106279-b41c9000-022f-11e9-8911-26119c7604d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Desktop PC
 - Browser Waterfox
 - Version 56.2.5

**Comment by Gaboris** [comment]
Actually that's not a bug. It's annoying, but not a bug.

The actual Discord client itself displays ALL unread messages like that and it seems that previous Franz versions were the ones that "filtered" for only mentions.
I was also kinda bummed out that that's not the case anymore, but I can't decide if that can be classified as an issue or not especially if some people might prefer it that way.

My personal idea would be an option to pick ALL or just mentions in the case of Discord, but I don't know how much extra work it would need to add an "exception" like that for a single service.

**Comment by PlaceboPRS** [comment]
Hmm well it makes me constantly think I have a new message to see so I'd say it's massively annoying and frustrating!

**Comment by Gaboris** [comment]
Hey @PlaceboPRS just in case you're interested I figured out a "hack" to solve this until it gets actually added, but you'll need to edit some really short code, but don' worry if you don't know how to.

Basically you need to type this into your File Explorer: %AppData%\Franz\recipes\discord
There you need to open webview.js with say the notepad.
Look around the 10th line. It should starts like this: "const indirect = document."
Change it so it looks like this: "const indirect = 0; //document."
Save the thing and reload the whole Franz client.

This shouldn't cause any problems since all you're doing is setting the number of indirect messages to 0 so Franz can't display anything for those, but if for some reason it's not working just tell me and I'll try to send you my own file somehow.

P.S.: This is only a temporary fix and if you update your Franz or delete the Discord tab you'll probably loose it and have to do it again, but it's still better than nothing, right? :)

**Comment by PlaceboPRS** [comment]
Perfect thanks I did that fix :)

**Comment by EinPinsel** [comment]
The hack from @Gaboris did work - thanks for that. I noticed this red bubble also in the full client, and there is an option for it to disable it (which is also available from the web view):
![image](https://user-images.githubusercontent.com/12642546/50582777-38dcf000-0e65-11e9-873b-817778187d9c.png)
For the desktop client it did the trick - but I have not checked outside of Franz

**Comment by jasmines** [comment]
I have a similar issue on Franz for Ubuntu (19.04 with Kde Environment).
The red dot is there even when all services are turned off.
I don't know what service caused the issue.
See the screenshot:
![Screenshot_20190509_125816](https://user-images.githubusercontent.com/894920/57448864-bd4bdf00-725a-11e9-8235-09e8be4f2f44.png)
