### ISSUE TITLE
WhatsApp crashing macOS Mojave 10.14.1

### ISSUE THREAD

**Issue by dawidadach** [meetfranz/franz#1201]
**Describe the bug**
Since a few updates, it's impossible to user WhatsApp service. As soon as I hit WhatsApp tabi it freezes the entire app, also the CPU usage bumps to 100% and everything is glitching until I kill Franz. The issue gets even worse when conversation contains images. 

**To Reproduce**
1. Go to WhatsApp tab
2. Click on a conversation with images

**Expected behavior**
Working and stable app

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.1

**Comment by eaorak** [comment]
I was searching for this issue. It happens with almost anything other than chat; while searching in conversations or looking for people, clicking videos and images and so on. As stated before CPU immediately hits 100% and application hangs.

OS: macOS Mojave 10.14

**Comment by nilber** [comment]
I'm having the same problem while trying to upload an image.

I drag the image to the talk screen, it takes 2min to display the Send option and my machine hits almost 100% CPU

**Comment by diegovigano** [comment]
I don't know if this is the solution, but it looks like it worked for me.
I simply forced a reload of the tab containing WhatsApp service, in order to download get the version. 

This can be done via pressing CMD + SHIFT + R  (with SHIFT pressed the webview is forced to download a fresh copy).

Hope it work for you too.

**Comment by diegovigano** [comment]
Small update. The method below doesn't always work. What seems to work is leaving the DevTool opened with the Disabled cache flag activated. It's a workaround while trying to find the real culprit.

**Comment by pthoelken** [comment]
Franz is based on the Chrome Kit. I think the first step to analyze the problem in detail, we should update the Chrome Kit to the latest version 71. Franz use version 61 atm. 

Btw: I have the same problem.

**Comment by Nornode** [comment]
I also have this issue... 
Performance issues seem to have gone away after I disabled GPU rendering (but started troubles with rendering the UI instead)

**Comment by pthoelken** [comment]
This can be only a workaround but not the solution for this case. As I told in #1204 , the developer should maybe integrate the newst version of chromekit in franz

**Comment by FlorianReznicek** [comment]
@diegovigano 

> What seems to work is leaving the DevTool opened with the Disabled cache flag activated

It **does** help to leave the devtools open, but for me it doesn't matter whether I check the disable cache option or not.
I think the positive effect of the open devtool bar is actually just the reduction in net window size. 😄  Because I can achieve similar performance improvement by just resizing franz to a smaller window.
The smaller I make it, the smoother it runs... uploading an image in fullscreen totally maxes out my CPU, in a smaller sized window it works just fine without noticeable performance issues.
