### ISSUE TITLE
Franz preventing windows from going to sleep/stand-by

### ISSUE THREAD

**Issue by vyruz1986** [meetfranz/franz#1202]
**Describe the bug**
I noticed my PC has problems going into stand-by mode when Franz is running. Typically I would troubleshoot this by running `powercfg /requests` in an admin command prompt, which showed me the following output:
```
powercfg /requests
DISPLAY:
None.

SYSTEM:
None.

AWAYMODE:
None.

EXECUTION:
[PROCESS] \Device\HarddiskVolume4\Users\Alex\AppData\Local\Programs\franz\Franz.exe
WebRTC has active PeerConnections

PERFBOOST:
None.

ACTIVELOCKSCREEN:
None.
```

So it seems Franz's WebRTC connections are preventing windows from sleeping?

Possibly same cause as #554?

**To Reproduce**

1. Have Franz running
2. Run `powercfg /requests` in an admin command prompt
3. Franz.exe will be listed as having WebRTC connections

**Expected behavior**
Franz should not have anything active which can prevent windows from sleeping

**Desktop (please complete the following information):**
 - OS: Windows 10 1803 x64
 - Chrome v71
 - Franz v5.0.0-beta.22

**Comment by aldorei9n** [comment]
Any luck with fixing this one vyruz? I have the same thing going on... I'm not sure if it is Franz causing my system not to sleep, but I get the same result from 'powercfg -requests' and my system won't sleep unless I click sleep or use the hard button set for sleep. My screen times-out as it should but the system doesn't send itself to sleep. 

Not sure if this part of the problem is related, but, if I hit a key or the touchpad just as the screen goes black it will come back... leave it any longer and ~99% of the time I can't get the screen to come back on and it will sit awake until I hard restart. Do you get that too, vyruz?
