### ISSUE TITLE
English UK Language

### ISSUE THREAD

**Issue by realdannys** [meetfranz/franz#1210]
Very simply - can we have an English UK dictionary, having to use US English is a nightmare for the rest of the world.

**Comment by stklik** [comment]
"hello"
Hi, I am from the "rest of the world" and I don't find en_US "a nightmare", but I'd also be interested in switching to en_GB.  (It helps since I write most emails in en_GB). Thanks in advance.
"please"

**Comment by ollietreend** [comment]
Leaving the disagreements in this thread to one side, I too would very much be interested in having a UK spelling dictionary available in Franz.

**Comment by PlaceboPRS** [comment]
Hello, I would very much please like British English, please and thank you, salutations and greetings, have a good day.

**Comment by closingin** [comment]
Apparently, translation requests should go [there](https://github.com/meetfranz/franz/issues/39) for languages that don't exist yet in the [translation tool](http://i18n.meetfranz.com/). You can also try to contact adlk on slack where there's a #translations channel, but it's kind of quiet.

To be honest, I don't think adlk is prioritizing it as the development stalled for some time because he was sick, but I'm sure he will take care of it asap !

**Comment by robinj** [comment]
We're not looking for an English language translation of the app, we just want UK English as a spell check language so that we can write without underlines everywhere.

**Comment by closingin** [comment]
> We're not looking for an English language translation of the app, we just want UK English as a spell check language so that we can write without underlines everywhere.

Oh, apologies!

**Comment by kwilczynski** [comment]
I would also love to the an ability to use British English.

**Comment by bovine3dom** [comment]
Live and working in 5.0.1-beta.1, so I think this issue can be closed. Thanks for the merge :)
