### ISSUE TITLE
Version upgrade issues

### ISSUE THREAD

**Issue by mnwalker** [meetfranz/franz#1290]
**Describe the bug**
On version 5.0.0-beta 18 and looking to upgrade, given that is suggested fix for current skype issue.

First issue, the automatic update is stuck forever saying "Is searching for update"

Second issue is trying the install the official version 5.0.0, ubuntu rejects the .deb saying "Already have a later version installed"
Numerically that is correct so a minor version bump to 5.0.1 would help people upgrade from the beta.

**To Reproduce**
1) Update via settings
2) Download latest deb from website

**Expected behavior**
Auto upgrade works
Install latest version has highest version number and works

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by arthurprs** [comment]
In the meantime people can do

```
sudo dpkg -i franz_5.0.0_amd64.deb
```

You'll see a warning like
```
dpkg: warning: downgrading franz from 5.0.0-beta.24-1110 to 5.0.0-1136
(Reading database ... 483366 files and directories currently installed.)
```

**Comment by meden** [comment]
Hello, I guess this problem does not have a solution, as current beta package uses an hyphen to separate the beta qualifier, instead of a tilde, which would allow an easier and more robust versions comparison.

The actual problem is that the hyphen in the version (allowed by the policy if also the package revision is specified) is present only in the beta packages, while the release version has it only to separate the Debian revision, so I guess `dpkg` is comparing different things. As letters are considered greater than numbers, `-beta.24-1110` results newer than `-1136`. See the [Debian Maintainer Guide](https://www.debian.org/doc/manuals/maint-guide/first.en.html#namever) and/or the [Debian Policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#versions) for further details.

To avoid this issue with _future_ beta packages, these should be versioned as
```
<version>[~betaQualifier][-packageRevision]
franz_6.0.0~beta1-1
```
where a tilde is used to separate the beta qualifiers and the Debian revision (always present) changes only when the packaging bits change (e.g. anything in `debian` folder), without any change in "upstream" code.

Thanks for your work!
