### ISSUE TITLE
Add service dark theming with Chrome extension Dark Reader

### ISSUE THREAD

**Issue by poisonborz** [meetfranz/franz#1309]
**Is your feature request related to a problem? Please describe.**
Dark mode is great, but services are still mainly light themed. Messenger and Whatsapp is basically the only white thing remaining on my desktop and its rather irritating.

**Describe the solution you'd like**
In browser, extensions like Dark Reader work great. Most services are darkened flawlessly. It does bit a little bit into rendering performance, but its more than worth it.
Modules like [this](https://www.npmjs.com/package/electron-chrome-extension) could be used to add (or enable the user to add) Dark Reader directly to Franz to dark theme services.

**Comment by Gaboris** [comment]
Custom themes are actually supported, but they need to be applied manually since we don't have a built in method to upload them yet.

For example I made my Messenger nice and dark with just a simple CSS I got from Stylish and several people here who figured out how to make it work. :D

Just download this or some other theme you like.
https://userstyles.org/styles/134433/dark-night-facebook-messenger
You might need to edit some themes to work. For example in this one you'd need to remove the first and last two lines of code. 
Then you need to add it to Franz's Messenger folder.
copy this into your file explorer %AppData%\Franz\recipes\messenger\ and save the theme as darkmode.css
Then you open Franz's settings, go the Services tab and pick Messenger where you need to enable dark mode.

If it doesn't work right away you might need to fully restart Franz and if it's still not working you might need some more help.

**Comment by poisonborz** [comment]
Thanks, thats a great solution for now.

Even so, the above feature/an extension would be much more useful:
- it works for every service
- its not a fixed stylesheet but a filter, so it works always regardless of future website changes

**Comment by danielfm123** [comment]
any way to make dark websites would be amazing... dark reader seems like a solution.

**Comment by Xerus2000** [comment]
Yep, not having this is super annoying. I have to add custom dark themes on every device individually and update them manually, what am I paying for? Supporting user-css in general with sync in my account would already be nice, since it also has auto-updates, but otherwise having something like Dark Reader would be really nice, since it's so versatile!

**Comment by xerus2000** [comment]
why does the stale bot only give 4 hours between marking as stale and closing?
