### ISSUE TITLE
Skype audio settings ignored

### ISSUE THREAD

**Issue by enrij** [meetfranz/franz#1408]
In Skype service if you set a default audio device/microphone to perform skype calls, Franz ignores the settings and uses the default devices instead (at least on Windows 10)

**Steps to reproduce the behavior**
1. Create Skype service
2. Log in with your account
3. Go to settings and change default playback device and/or mic

![image](https://user-images.githubusercontent.com/13519234/56596787-7b336400-65f1-11e9-9ca8-174b3b827098.png)

**Expected behavior**
Hear and speak to the selected devices

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Franz 5.0.1

Performing the same operations on https://web.skype.com/ works like expected

**Comment by Gittyperson** [comment]
Same as above, and also: I'm trying the Franz Skype service and while video works on the test call and settings, audio does not. Neither the speaker audio test nor the microphone input work. Does Franz only use Skype for Web or perhaps it also relies on the installed Skype client? In any case, Skype is currently unusable for calls.

Windows 10 1903 x64
Skype 8.47.0.59 installed (works fine)
Franz 5.1.0

**Comment by enrij** [comment]
Up!!!!
This issue is VERY annoyng and forces me to use Skype App everytime i need to make a call

**Comment by hcp-coder** [comment]
There is a community edition called Ferdi. It's a fork of this project but is actively maintained and works amazingly. Give it a go: https://github.com/getferdi/

Unfortunatetly Franz does not seem to be developed actively. There is no support contact for paying customers. It seems that someone is maintaining it since they are offering discounts from time to time.

The mic and video problem is solved with the community edition (v5.4.3).

I would like to support Franz but not sure if it is maintained anymore,
