### ISSUE TITLE
Add an option to disable the popups.

### ISSUE THREAD

**Issue by ccccyes** [meetfranz/franz#1436]
**Is your feature request related to a problem? Please describe.**

Seen a few popups like this recently: https://i.imgur.com/qAn95tW.png

Please don't do this. I am a free user, but I'd even rather you insert Adsense than stuff like this. Franz seems to be getting a little bloated in the past few updates, leave it as it is.

**Describe the solution you'd like**

**Describe alternatives you've considered** 

Option to disable these popups.

**Comment by nokeechia** [comment]
These are not ads per se, but just reminders to vote if you live in the EU. I am guessing it is important to them hence why it was added.

**Comment by sebna** [comment]
In any case - that´s not professional.

**Comment by closingin** [comment]
Hello,

What is the problem ?
- Close the message if you don't want to see it
- Don't use the software if you don't like what the developers do with it

As @nokeechia said, this message comes from the [News API](https://github.com/meetfranz/franz/blob/master/src/api/server/ServerApi.js#L422) of the application. This news has certainly been written by the devs because they care about politics. Anyway, this message does not ask you to vote for a certain list, but just to vote. Maybe you don't like voting, but it's up to you!

I agree with the idea of adding an option to disable news messages, but looking at the way you wrote your issue, it just makes me want to ignore this proposal.

You want this software to be professional ? Be professional yourselves, open your issue with an appropriate clickbait-free title and be nice.
