### ISSUE TITLE
Add keyboard shortcut option to disable/enable service

### ISSUE THREAD

**Issue by wzuo** [meetfranz/franz#144]
### Feature Description
Using shortcut, for example alt+left mouse click on service's tab should disable it and make it gray colored. Clicking again with this modifier should enable it again. 

### Motivation and Context
Currently I'm using Franz for work and personal communicators. I want to disable work/personal communicators based on day and hours. I don't want to receive messages from job after hours, and personal ones while working, as this is disrupting.

**Comment by brendanjones** [comment]
+1 to this. In the absence of reintroducing the service on/off switcher (#449 ), or even as a complementary feature to #449, it's be great to be able to switch a service on/off with a keyboard shortcut. Because keyboard shortcuts are da bomb.

- Keyboard shortcut something like Command/Cntrl+o+[service number 1,2,3,etc]. Though, command+o would conflict with #284 and normal app UX, so maybe a different key.
- Functionality: You could have the option in preferences whether to switch to the activated app when turned on, or to stay on current service. Turning off the service would remain on the service.

**Comment by adlk** [comment]
I'm all in for adding a shortcut but would keep it as simple as possible. You need to navigate to a service and then press the shortcut. Not sure yet what a good key combination is. Any suggestions?

Ad preferences: I'm not a big fan of adding too many options to the settings. I know that a lot of people love to customize everything to the fullest but we've learned in the past that most of those features are hardly used at all and generate a lot of confusion with users who just want Franz to work.

**Comment by haraldox** [comment]
IMHO right-clicking is easier... closing this as there are no shortcut suggestions, feel free to reopen!

**Comment by AnthoPakPak** [comment]
I'm also looking forward for a way to disable without having to right click. At least, you can add a line in menu bar, so that each person can assign the shortcut they want through System Preferences.
Thanks 🙏

**Comment by alvarotroya** [comment]
I am also looking for this option, have there been any changes since 2019 regarding this feature? Many thanks for your feedback!
