### ISSUE TITLE
Mic no longer works in Franz as of windows 10 version 1903

### ISSUE THREAD

**Issue by maryadavies** [meetfranz/franz#1482]
To reproduce this:
1. Install Franz on this version
2. Try to unmute the mic on Discord.
3. It asks for permission, BUT the popup never pops up.

Can you check this please? I think Windows broke the mic in this, the only workaround is to use the official discord for now.

**Comment by pit-c** [comment]
There is a community edition called Ferdi. It's a fork of this project but is actively maintained and works amazingly. Give it a go: https://github.com/getferdi/

Unfortunatetly Franz does not seem to be developed actively. There is no support contact for paying customers. It seems that someone is maintaining it since there are offering discounts from time to time.

The mic and video problem is solved with the community edition (v5.4.3).

I would like to support Franz but not sure if it is maintained anymore,
