### ISSUE TITLE
Franz is not starting up

### ISSUE THREAD

**Issue by ItzSheldor** [meetfranz/franz#1512]
### Expected Behavior
When i click the icon in the taskbar, franz should start.

### Current Behavior
If i click, nothing happens. In the Taskmanager you can see Frany as Backgroundprocess.

### Screenshots (if appropriate):
![Backgroundprocess](https://user-images.githubusercontent.com/36795157/60375795-59989380-9a0b-11e9-8db0-b01e6e6ee892.png)

### Your Environment
i9 9900k, 32GB DDR4
* Franz Version used: 5.1
* Operating System and version: Windows 64bit 1809

**Comment by aduenape7** [comment]
i faced the same some weeks ago. I tried to reinstall it but it didn't work...

**Comment by easylite376** [comment]
Look into this [comment](https://github.com/meetfranz/franz/issues/222#issuecomment-359207761) in #222 

It might help. Did you update your graphics card driver while franz was opened or remove a display from your laptop?

**Comment by ItzSheldor** [comment]
> It might help. Did you update your graphics card driver while franz was opened or remove a display from your laptop?

No. Just didnt started anymore. :C

**Comment by nairbd** [comment]
Having the same issue. Been using Franz since v4 and have been upgrading with each version. The latest just stopped working. It launches and shows in the Task Manager, but no icon in the taskbar. I have dual monitors connected to a usb-c hub connected to my laptop.

Have also had the windows disappear, so knowing to delete the window-state.json is helpful for the future, but doesn't solve the current issue. It's been about a week that I haven't been able to get Franz to launch. Today I uninstalled and reinstalled 5.4.1 from the releases GitHhub.

**Comment by nairbd** [comment]
Not sure why this was closed, it's still not fixed. I haven't been able to use Franz since my last comment a year ago. I just downloaded the newest version and same exact thing happens, the process shows up under the Task Manager, but there is no visible Franz application window.
