### ISSUE TITLE
Starting Franz.exe from Windows CMD.exe hangs from build/upgrade response

### ISSUE THREAD

**Issue by xodarap777** [meetfranz/franz#1525]
When Franz checks for update when started from cmd.exe, the response hangs the cmd window, even when called with start, e.g. `>start ...franz.exe`.

I lost the example for a screenshot or direct report of the response.  It says something about no upgrade being available, then just hangs in the command window.  The CMD window oddly becomes associated with Franz.exe in Windows, so that even `>taskkill.exe /im cmd.exe /f` - despite reporting success in killing all cmd.exe processes - does not kill the window.  The window is also associated after that point with the Franz icon on the Windows taskbar.

**Comment by zhubanRuban** [comment]
I can confirm the described behavior.

Steps to reproduce (Windows 10):
1) create launch.cmd file with the following content:
```
@echo off
start "" "%LOCALAPPDATA%\Programs\franz\Franz.exe"
start "" explorer
```
2) launch launch.cmd

Result:
- Franz is launched
- explorer is launched after Franz
but Franz keeps writing messages in cmd window (update checks etc.)
Ctrl+C stops this, but Franz is closed as well
If you close cmd window, Franz is closed too

Expected behavior:
- Franz is launched
- Franz does not write messages in cmd window
- Franz is not closed when you close cmd window
