### ISSUE TITLE
WhatsApp Service wants Chrome 49+

### ISSUE THREAD

**Issue by sreuterle** [meetfranz/franz#1540]
**Describe the bug**

**To Reproduce**
* Start Franz App and open a WhatsApp Service

I am using the latest Franz version (5.2.0), no update available; even in beta there is no update.

**Expected behavior**
To see the usual WhatApp Messenger Window

**Screenshots**
![Bildschirmfoto 2019-07-24 um 13 29 32](https://user-images.githubusercontent.com/11695741/61790469-93489880-ae17-11e9-8bbc-d71f84f870c1.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - local installed Browsers available: 
    - Safari 12.1.2
    - Chrome (75.0.3770.142)
    - Firefox 66.0.3

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: latest stable iOS
 - Browser: stock browser, safari
 - Version: latest

**Additional context**

**Comment by Fepreitas** [comment]
Here you have the known work arounds #1185 

For me, reloading the browser does the trick (Cmd/Ctrl+R)

**Comment by romanmorozov81** [comment]
I have the same problem

**Comment by sreuterle** [comment]
Try Reload with Cmd+R. Worked for me.

**Comment by napgab** [comment]
> Try Reload with Cmd+R. Worked for me.

Not for me

**Comment by sv1266** [comment]
I am having the same issue on Windows.

**Comment by sv1266** [comment]
I'm on the windows version and currently I don't have a subscription but I figured out a workaround that only needs to be set once -- then it'll automatically load without any problems. I hope this works for your guys on Mac and for people with paid subscriptions:  

Go to C:\Users\[Username]\AppData\Roaming\Franz\recipes\whatsapp (or the mac equivalent)
Open the webview.js file in an editor. 

**Modify the line:**

 if (elem && elem.innerText.toLowerCase().includes('google chrome')) {
    window.location.reload();
  }
}, 1000);

**to:**
if (elem && elem.innerText.toLowerCase().includes('google chrome')) {
    window.location.reload();
  }
}, 8475);

This workaround will automatically refresh the page without user interaction, but will flash the screen showing that WhtasApp wants Chrome 49+.  For some reason, shorter delays don't refresh (maybe because I am on the free version.) If you have a paid subscription, it is possible that lowering  this number for a shorter delay will work for you.

If this solves your problem, let me know so I an make these changes to the code in the main Recipe-WhatsApp repo.

**Comment by starchild** [comment]
Thank you.

This fixes it for me, but I still have to hit CMD R to remove the notice.

**Comment by sv1266** [comment]
Really, you shouldn't have to.
If your willing to fiddle with it, try setting it to 10000 and wait 15 seconds. 

It's should load without you having to do anything.

**Comment by starchild** [comment]
what crazy lifestyle do you have where you have a lazy 15 seconds!? lol.  ok will try.
