### ISSUE TITLE
Android messages won't open (error: 400)

### ISSUE THREAD

**Issue by marcolopes** [meetfranz/franz#1575]
ANDROID MESSAGES won't open. Shows browser error:

**400. That’s an error.
The requested URL was not found on this server. That’s all we know.**

**Comment by maryadavies** [comment]
I've been getting the same error. Reloading it seems to fix it, but I think someone needs to check this.

I'm on 5.2.1 beta 1.

**Comment by cdnnhicks** [comment]
I've had the same issue for a few days. Sometimes a reload will work. Other times, I have to remove and add the service completely. I'm running Win 10 1903 and Franz version 5.2.0

**Comment by marcolopes** [comment]
RELOAD won't fix in my case... Franz restart won't fix either.

**Comment by k1sr** [comment]
Not working here either, although the website and PC app work fine, which seems odd, given Franz is really just a wrapper for the web app... Unless they've added something to check if you're using a 3rd party app to access the url??

**Comment by misteroh** [comment]
Crappy temporary bandaid "fix" here:

1. Open `View` > `Toggle Service Developer Tools (Ctrl/Cmd + Shift + Alt + I)`
1. In that new section that showed up, do you see that topbar with `Elements` / `Console` / `Sources` / `Network` / `Performance` / `Memory` / `Application` / etc...? Click on `Application`
1. On the left hand side, click on `Service Workers`
1. Click on the checkmark that says `Bypass for network`

Now as long as you have this Developer Tools window open, Android Messages will work even if you refresh.

Not ideal obviously but it will make do until this is fixed.
--------------------------------------------------

Poking around in the dev tools, I think the issue is centered around a service worker.

On initial load, `https://messages.google.com/web/` loads fine and it spins up a service worker I assume for offline mode and other features. In any subsequent reload, the service worker intercepts the GET to `https://messages.google.com/web/` and returns a `400` which displays the error message we're all seeing now. Why? I'm not really sure.

**Comment by maryadavies** [comment]
Thank you. Hopefuly there can be a more perm fix.

**Comment by Paladin173** [comment]
getting same issue on my end.

**Comment by pllgr** [comment]
same issue. My temp fix is deleting the service, re adding it.
Works for a few days then stops working

**Comment by Paladin173** [comment]
> 
> 
> Crappy temporary bandaid "fix" here:
> 
>     1. While in the Android Messages service, open `View` > `Toggle Service Developer Tools (Ctrl/Cmd + Shift + Alt + I)`
> 
>     2. In that new section that showed up, do you see that topbar with `Elements` / `Console` / `Sources` / `Network` / `Performance` / `Memory` / `Application` / etc...? Click on `Application`
> 
>     3. On the left hand side, click on `Service Workers`
> 
>     4. Click on the checkmark that says `Bypass for network`
> 
> 
> Now as long as you have this Developer Tools window open, Android Messages will work even if you refresh.
> 
> Not ideal obviously but it will make do until this is fixed.
> 
> Poking around in the dev tools, I think the issue is centered around a service worker.
> 
> On initial load, `https://messages.google.com/web/` loads fine and it spins up a service worker I assume for offline mode and other features. In any subsequent reload, the service worker intercepts the GET to `https://messages.google.com/web/` and returns a `400` which displays the error message we're all seeing now. Why? I'm not really sure.
> 
> @adlk or @dweinberdweinber thoughts?

Easy fix it seems, why hasnt it been implemented yet?

**Comment by themagpieswarble** [comment]
> @marcolopes
> You don't need to remove and add the service as long as the Developer Tools window is open.

Not working for me either. 

I load in Android Messages as a new service just to start fresh, while it's still working I follow your directions, I right click Android Messages and click 'Reload' to test it, and it loads with the 400 error. Doesn't matter if Dev Tools window is still open on the side with the 'Bypass for network' box checked and/or the 'Update on reload' box is checked (like someone suggested in another thread.) 

I've also tried doing this after Android Messages 400 error appears and it doesn't seem to matter.

How annoying. Seems like this would be an easy fix and it's been going on for over a month now.

**Comment by ryan-rokusek** [comment]
The workaround isn't working for me either. 

OSX: 10.14.6
Franz: 5.3.3

**Comment by maryadavies** [comment]
Finally found a fix since my Franz stuffed up..again..after a reboot and would not fully load. #$%^%#$! Fixing that also fixed the Android Messages problem.

You guys need to do a clean install, that means get rid of the profile folder.

To do this:
1. Uninstall Franz. Completely.
2. Hit Windows Key + R, then type %APPDATA%. Kill the Franz folder (as in delete it), click back a step, go to local, and kill the franz-updater folder too.
3. Reinstall the newest version, once you log in your stuff, it should work now and be solid as a rock. No more 400 error.
