### ISSUE TITLE
Android messages

### ISSUE THREAD

**Issue by Romainpetit** [meetfranz/franz#1583]
**Describe the bug**
Android messages service is not working anymore, displaying a 400 error.
Was closed here : 
https://github.com/meetfranz/franz/issues/1017

**To Reproduce**
1. Go to 'Add a new service'
2. Click on 'Android messages'
3. Setup using QR code
4. See 400 error

**Expected behavior**
No error, service visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/632197/63954696-c9ff7780-ca83-11e9-8897-4501cf863699.png)

**Desktop:**
 - OS: MacOs
 - Browser: Franz Desktop App
 - Version -

**Comment by MikeInNY** [comment]
Same issue here

**Comment by mastercko** [comment]
Same.

**Comment by ben42210** [comment]
Same issue.

sometimes, by removing the service, disconnecting the clients on the application messages and adding the service it works again ... but not always

Version : 5.2.0 on MacOs

**Comment by misteroh** [comment]
Duplicate of https://github.com/meetfranz/franz/issues/1575

Here's a crappy workaround for now
-----------
Crappy temporary bandaid "fix" here:

1. While in the Android Messages service, open `View` > `Toggle Service Developer Tools (Ctrl/Cmd + Shift + Alt + I)`
1. In that new section that showed up, do you see that topbar with `Elements` / `Console` / `Sources` / `Network` / `Performance` / `Memory` / `Application` / etc...? Click on `Application`
1. On the left hand side, click on `Service Workers`
1. Click on the checkmark that says `Bypass for network`

Now as long as you have this Developer Tools window open, Android Messages will work even if you refresh.

Not ideal obviously but it will make do until this is fixed.

--------------------------------------------------

Poking around in the dev tools, I think the issue is centered around a service worker.

On initial load, `https://messages.google.com/web/` loads fine and it spins up a service worker I assume for offline mode and other features. In any subsequent reload, the service worker intercepts the GET to `https://messages.google.com/web/` and returns a `400` which displays the error message we're all seeing now. Why? I'm not really sure.  

@adlk or @dweinberdweinber thoughts?

**Comment by PerkyFerret** [comment]
Same error Mac OS X El Capitan v10.11.6
Franz 5.2.0 (5.2.0.1455)
Suggested workaround by **misteroh** doesn't work for me :(

**Comment by stacksjb** [comment]
Mine worked after checking "Update on reload" and then reloading the service.

**Comment by PerkyFerret** [comment]
Thank you, that worked :)

**Comment by stacksjb** [comment]
Any way you could just force "update on reload" on all reloads as a temporary workaround?

**Comment by MikeInNY** [comment]
Where is "Update on reload" ?

**Comment by stacksjb** [comment]
Under Toggle Service Developer Tools -> Application -> Service Workers (same as comment above https://github.com/meetfranz/franz/issues/1583#issuecomment-526557441)
![image](https://user-images.githubusercontent.com/2865491/64195850-b1a2aa80-ce3f-11e9-90e6-d896a0551d01.png)

**Comment by MikeInNY** [comment]
> Under Toggle Service Developer Tools -> Application -> Service Workers ( [#1583 (comment)](https://github.com/meetfranz/franz/issues/1583#issuecomment-526557441))
> ![image](https://user-images.githubusercontent.com/2865491/64195850-b1a2aa80-ce3f-11e9-90e6-d896a0551d01.png)
> Checking the box, then reloading the service worked for me.

Got it, thanks!

**Comment by Lefky** [comment]
Confirming **version 5.3.3** still has the issue.
Also, none of the fixes seem to work for me.

**Comment by stacksjb** [comment]
Try clicking "Unregister" and then refreshing... after tryin gall of the others, that has become the only one that seems to work 100% reliably.

**Comment by francwalter** [comment]
Still unfixed on Mac 10.11.6 with Franz 5.3.3
The fix with dev tools (Thanks!) worked, but I would prefer a lasting solution.

**Comment by Lefky** [comment]
So....
I've got some good news and some bad news.
The good news is I made my own version that's working. 
The bad news is that I'm not sure it's the most efficient way to do it and I'm not sure if it's a permanent fix. Also the badge counter doesn't work.

So if someone can help me fix these things (especially the badge counter) that'd be great.
If anyone encounters any bugs also let me know.


[Android-Messages-bugfix.zip](https://github.com/meetfranz/franz/files/3716221/Android-Messages-bugfix.zip)

To install follow the steps in the readme here: https://github.com/jvdmeij/recipe-franz-website
Just replace step 1 with my zip file.

**Comment by Lefky** [comment]
I found a permanent fix for this.
I recently had my computer reinstalled and the issue just disappeared. So I'm guessing if you delete franz completely it works again.
To COMPLETELY delete franz you have to remove all references to franz from these 2 paths:
```
%appdata%\Roaming\Franz
%appdata%\Local\Programs\Franz
```
You can access those paths using windows explorer and entering these in the navigation bar.
Mac users can follow this: https://macuninstallguides.com/remove-franz-on-mac.html

When you reinstall it should work.
