### ISSUE TITLE
"Franz Todos" tab is appearing on top of service area

### ISSUE THREAD

**Issue by andytuba** [meetfranz/franz#1600]
**Describe the bug**
Franz Todos tab is appearing on top of my other services/apps.

**To Reproduce**
1. Upgrade to v5.3.0
2. Open any given service
3. See a blue tab overlaid on the service

**Expected behavior**
I'd prefer the Todos tab to either be siloed off in the navigation menu on the left with the other services or system features, or to disable Franz Todos entirely.  (I use Trello and Todoist for my todos.)

**Screenshots**

![Franz "todos" tab showing inside the Franz app, attached to the right edge](https://user-images.githubusercontent.com/455632/64460812-47dd0780-d0b0-11e9-98e1-298a538604fb.png)

from @HarderBetterFasterStronger:
!["Todos" tab blocking Slack UI](https://user-images.githubusercontent.com/3767294/64465365-289aa600-d0c1-11e9-894c-520cfe916b5f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  macOS Mojave 10.14.5
 - Browser [e.g. chrome, safari]: Franz
 - Version [e.g. 22]: v5.3.0.1519

**Additional context**
No, I don't want to just ignore the existence of the tab over there, since it's interfering with services' UI.

**Comment by HarderBetterFasterStronger** [comment]
+1 for `or to disable Franz Todos entirely`

A few comments:
1.  I feel the to-do feature could be powerful, but I really hope it was thought out fully in terms of design.  The appeal of Franz, for me, is the ability to isolate all my services in to one app container while keeping original features available via that service's web view.  It lets me choose where to keep my focus and this is obviously known to Franz as the workspace feature attempts to assist with this further.

I want to relate this to the to-do list and ask whether it adheres to these principles.  It appears to me that the to-do list is a giant, everything goes list that spans across Franz as a whole.  If this is the case, I would suggest that the feature is no better than a cloud sync notepad/list and let's be real - there are much better tools for that out there.

Now, that said, I do believe that this feature could be useful, but it would have to maintain the idea of a per service level focus.  In other words this:
- A `to-do` should have the option of being applicable at a singular, service level
- A `to-do` should have the option of spanning multiple services without needing to be duplicated to a new list
- A `to-do` should have the option of spanning across workspaces
- A `to-do` should have the option of being shared among teams (team members/teams)
- A `to-do` and all `to-do` lists should be synchronized via account/cloud

Anyway, I would look at that list and wonder if this is feature is worth pursuing.  Not to sound harsh, but I would guess there are many other issues that could be pursued to enhance the Franz core product offering/appeal which is isolating a user's services (web views) in to a single app container while maintaining the identical functionality of the original serivce(s) web view(s).

2.  @andytuba Makes great points about:
- This feature should be able to be disabled.  People already have a to-do application of their choice.  Also, no offense:  but these apps are definitely more feature rich with all kinds of things like multi-list/scheduling/alerts/sharing.
- The placement of this floating tab.  This is actually probably what needs to be stressed most.  The UX on this.  Bad.  Actually very distracting.  I like his suggestion of putting in the nav bar to the left (condition: if the feature is enabled.  Otherwise, hide).  If the idea is pulling out list on text highlight, then have a subtle drawer fly out like you would do when clicking the nav icon.

3.  This is one of those scary moments when it feels something was pushed out quickly and then forced on users.  It makes me wonder how many other features (and features I will probably not use  as well) will be slapped on without the ability to disable.

Anyway, sorry for the long post, but I like your product very much and want to continue promoting it to others.  And who knows, maybe everybody loves it and I'm totally off.  I would just let the data speak for itself though and 1. make it easy to enable/disable and then 2. metrics/track (anonymously) how many people enable vs. disable the feature.

Also, I will attach a picture showing also why placement is bad choice.
<img width="236" alt="placement" src="https://user-images.githubusercontent.com/3767294/64465365-289aa600-d0c1-11e9-894c-520cfe916b5f.png">

**Comment by andytuba** [comment]
Interesting side note: the Todos app is essentially another service, hosted at https://app.franztodos.com

**Comment by HarderBetterFasterStronger** [comment]
Just wanted to say thank you for amazing response time giving the ability to disable this by @adlk in [Release v5.3.1](https://github.com/meetfranz/franz/releases/tag/v5.3.1)

Thank you.  Not sure if it was meant as response to this, but thank you if so.

**Comment by andytuba** [comment]
👍 Thanks! https://github.com/meetfranz/franz/commit/5d03b91dd789ffd6d3d5753c223b4b6412887220
