### ISSUE TITLE
Slack Calls Open in Browser

### ISSUE THREAD

**Issue by Ninpo** [meetfranz/franz#1603]
**Describe the bug**
Until recently, Slack calls worked fine in Franz. Now when attempting to start a call in Franz, it opens a link in my browser instead (and the call does not work).

**To Reproduce**
1. Go to an active Slack service
2. Click on any other user
3. Click the Call icon
4. Tab opens in browser instead of a call popup

**Expected behavior**
A new Franz window containing the call opens.

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser Firefox
 - Version Franz 5.2.0 - 5.3.1 inclusive

**Comment by blaise-io** [comment]
I have the same issue.

Mac OS Mojave 10.14.6 (18G87)
Firefox 70
Franz  5.3.1 (5.3.1.1528)

Note that the call popup doesn't work in Firefox, even when I'm logged in to Slack on Firefox. This is probably because the call has an identifier that is bound to my Franz login session and not to my Firefox login session.

**Comment by hoektoe** [comment]
After I make a call and it gets declined, I cannot re-attempt to make the same call again at all

**Comment by Ninpo** [comment]
> After I make a call and it gets declined, I cannot re-attempt to make the same call again at all

Ah yes I forgot this one. Subsequent attempts to start calls after the first opens a browser window, do nothing.

**Comment by enryIT** [comment]
Any solution?
