### ISSUE TITLE
Messages is 404ing again

### ISSUE THREAD

**Issue by awgordon** [meetfranz/franz#1619]
Version 5.3.3 (5.3.3.1582) 

Refreshing/reloading the app doesn't help

**Comment by maryadavies** [comment]
okay. I finally found a fix since my Franz really started not loading when I loaded it (no window) @#$%%^! Unfortunately it's the nuke it from orbit option:

1. Uninstall Franz. Completely.
2. Hit Windows Key + R, type in %APPDATA%, then nuke the Franz folder. Go back a step, hit local, and nuke the franz-updater folder too.
3. Reinstall the latest version. You should be happy now; after I did all that, my Android Messages started working properly again.

**Comment by awgordon** [comment]
Would this work on Mac too? I'd just have to find where the App data is I guess.

**Comment by maryadavies** [comment]
It prolly would but I am first to admit, I'm more familiar with MS than Apple.
