### ISSUE TITLE
Slack calls without microphone and camera on MacOS

### ISSUE THREAD

**Issue by fwentz** [meetfranz/franz#1700]
**Describe the bug**
When starting a call in Slack, voice input and camera are not working.

**To Reproduce**
1. In any slack account, navigate to a group
2. Click on the phone icon on top to start a call
3. Choose any input device for sound and image
4. No error is thrown, no system message about accessibility rights in settings is shown, microphone and camera are not used

**Expected behavior**
Webcam and microphone are used. If rights are not granted in accessibility tab, a system message is shown to inform the user.

**Screenshots**

![Bildschirmfoto 2019-11-18 um 14 49 20](https://user-images.githubusercontent.com/4090501/69057863-d0621780-0a12-11ea-826f-b000594547cc.png)

**Desktop:**
 - OS: MacOS 10.14.6
- Franz Version: 5.4.1

**Additional context**
Checking the accessibility tab reveals that there are no entries for Franz for microphone and webcam.

**Comment by danielDevelops** [comment]
I am having the exact same issue.  MacOS Mojave

**Comment by bennypowers** [comment]
Slack app doesn't ask for mic permissions, so I had to go to System Prefs > Security & Privacy > Microphone, and add Slack to the approved apps

**Comment by pit-c** [comment]
There is a community edition called Ferdi. It's a fork of this project but is actively maintained and works amazingly. Give it a go: https://github.com/getferdi/

Unfortunatetly Franz does not seem to be developed actively. There is no support contact for paying customers. It seems that someone is maintaining it since there are offering discounts from time to time.

The mic and video problem is solved with the community edition (v5.4.3).

I would like to support Franz but not sure if it is maintained anymore,

**Comment by svallier** [comment]
You can open Franz with terminal who ask for microphone permissions. So the workaround could be simply to open it through terminal on boot

/Applications/Franz.app/Contents/MacOS/Franz &

**Comment by Cahl-Dee** [comment]
Here's this GitHub [issue](https://github.com/getferdi/ferdi/issues/154) and [pull request](https://github.com/getferdi/ferdi/pull/193) where they solved this bug over at Ferdi. Hoping someone can port over the fix before I need to bounce over to using their service instead.
