### ISSUE TITLE
Microphone doesn't work (Slack, Chanty)

### ISSUE THREAD

**Issue by perolowa** [meetfranz/franz#1743]
**Describe the bug**
Whenever I make a call with slack or chanty, I can hear the other person but they cannot hear me. Everything seems ok but no one can hear me. 

**To Reproduce**
1. Go to any chat
2. Click the call button
3. Wait till you hear the other person saying "hello?" all the time

**Expected behavior**
The other person should also hear me.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.2

**Comment by togakangaroo** [comment]
Me too, same OS.

I suspect it is because franz never asks for mic permissions but each of those apps explicitly do

**Comment by mhauens** [comment]
Same for me with macOS Catalina 10.15.3. Franz doesn't show up in the microphone permissions.

**Comment by HatBeardMe** [comment]
Same for me with macOS Catalina 10.15.3 with Franz 5.4.1
Doesn't prompt for Microphone access and I don't know a way to force add it.

As a workaround, `/Applications/Franz.app/Contents/MacOS/Franz &!` (run from the terminal) will open Franz with the terminal's permissions - and if you go to create a voice chat, the terminal will ask for Mic permission. 

Working for me for Discord

**Comment by sherifkandeel** [comment]
@HatBeardMe Nice, that worked for me for Slack. I also have permissions for slack native app itslef enabled, if that helps anyone

**Comment by pit-c** [comment]
There is a community edition called Ferdi. It's a fork of this project but is actively maintained and works amazingly. Give it a go: https://github.com/getferdi/

Unfortunatetly Franz does not seem to be developed activly. There is no support contact for paying customers. It seems that someone is maintaining it since there are offering discounts from time to time.

The mic and video problem is solved with the community edition (v5.4.3).

I would like to support Franz but not sure if it is maintained anymore,

**Comment by sherifkandeel** [comment]
@adlk any thoughts about this?

**Comment by nguyenphucthinh** [comment]
hey, my No-Code and No-Terminal Solution
- open camera and microphone permission for Franz in your MacOS 
`
Preferences > Security & Privacy > Privacy > Select Franz for Microphone / Camera and Screen Recording (optional)
`

Hope this tips can help you

**Comment by nguyenphucthinh** [comment]
Franz can not make call with audio because Permission Microphone is closed for Franz >>> Just open this permission in Security and Privacy
