### ISSUE TITLE
Usability problems missing navigation bar

### ISSUE THREAD

**Issue by rehoehle** [meetfranz/franz#185]
I use the new Franz now for some days and i found some usability problems that makes some problems for me. 

When you have a service like Github here in the window. And you click through the page it happens that you come to a page where you have no backbutton and you can't go back to site before and you stuck. 

For embedded sites it would be very helpfull to have a navigation bar to navigate back.

Otherwise you have to disable the service and enable it again.

**Comment by alecive** [comment]
I think this is related to https://github.com/meetfranz/franz/issues/135 . Theoretically, any external link should be opened in a browser and not opened in franz itself.

**Comment by rehoehle** [comment]
Yes but it would be cool if you can navigate back. Would much easier.

**Comment by adlk** [comment]
The actual issue is that Franz is not meant to display other things then a web app like a messaging service where you don't follow traditional navigation patterns as you do in a browser. 

With opening up Franz and the option to add community services in the app we get services like Github where the official use case of Franz is defied. This leads to exactly the problem you described. Technical infrastructure aside, Franz is not designed to be a browser.

Of course we could simply add navigation controls but the reason why Franz works so well is its incredible simplicity which is achieved by *not* building yet another browser.

Off the top of my head we have these options:
- _Low hanging fruit:_ add a check in the Github recipe to open links that are leaving github.com in a new window
- Have a stricter content policy to disallow non app-like services

**Comment by alecive** [comment]
I think that the stricter content policy would greatly limit the potentialities of this app. But it makes sense in terms of UX for these issues not to arise in the first place, so I would be in favor of the first solution. And that should apply to the GitHub recipe AND everything else that may have the same issue.
