### ISSUE TITLE
Gmail notifications display when disabled

### ISSUE THREAD

**Issue by mattgreenfield** [meetfranz/franz#246]
I have disabled notifications for all services in the Franz settings. This works for whatsapp and telegram but it is not working for gmail, I still see the notification. Interestingly, the notification doesn't appear in the OSX 'notification center'

### Expected Behavior
No notification should show when a new message is recieved

### Current Behavior
A notification is show in the top right of my screen (OSX) with the Franz logo and a summary of my gmail email.

I guess the first step is to see if anyone else can replicate it?

### Your Environment
* Franz Version used: 5.0.0-beta. 13
* Operating System and version: OSX Sierra 10.12.4

**Comment by OscarAbadFolgueira** [comment]
I have the same problem...

**Comment by ducarpit** [comment]
If you close and reopen your Franz app, the app works fine? Or there is the same problem?

**Comment by mattgreenfield** [comment]
I've been quiting and re launching since I raised the issue with no
improvement.

Do you mean an update has been released recently?

Thanks

**Comment by haraldox** [comment]
@mattgreenfield any news?

**Comment by mattgreenfield** [comment]
I'm afraid not. I've stopped using Franz for Gmail

**Comment by mideeks** [comment]
I am also getting this on the latest version 5.0.0-beta.18 on Mac High Sierra. It is because I had "Desktop Notifications" enabled in Gmail itself. If you turn this off, then you won't get them. 

![image](https://user-images.githubusercontent.com/11986899/38636068-142bfb58-3d7c-11e8-8374-dd370bc92a19.png)

The fix for Franz is that it should intercept these notifications (if possible) and turn them off if I have notifications turned off in Franz itself.
