### ISSUE TITLE
Franz doesn't install properly on High Sierra (App Translocation & Little Snitch)

### ISSUE THREAD

**Issue by FlyingBarney** [meetfranz/franz#271]
### Screenshots (if appropriate):

<img width="582" alt="image" src="https://user-images.githubusercontent.com/33645692/32760736-8530e874-c8a4-11e7-8013-88d649c2f700.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/33645692/32760744-8d750bfa-c8a4-11e7-8dfe-841dc3e8532d.png">

### Steps to Reproduce (for bugs)

1. When I start Franz the first time, Little Snitch complains about Franz running in App Translocation. Yet, Franz is clearly sitting in the Applications folder.
2. Once Franz is running, there are not problems. Until I quit and restart, which is when it appears again.
3. It happens every time I start Franz for the first time.
4.

### Your Environment

* Franz Version used: 5.0.0-beta 13 (5.0.0-beta.13.316)
* Operating System and version: macOS High Sierra 10.13

**Comment by adlk** [comment]
Since the app is distributed via a DMG you have to drag & drop the App to your Applications Folder. So there is no actual installation involved. However, it could be an issue with auto updates and Gatekeeper.

What you can try to do to solve this is to open Terminal and run this command:
`sudo xattr -dr com.apple.quarantine /Applications/Franz.app/`
Then start the app, set the little snitch rules. When restarting the app, little snitch should not ask again.

You can get more information here:
https://blog.obdev.at/gatekeeper-and-little-snitch-rules/

**Comment by FlyingBarney** [comment]
Thank you, Stefan. The xattr command worked, and then when I started Franz, I got a message saying I need to update the code signature. So now it works like a charm - thank you for your prompt help, and for the good work with the app. I appreciate it.

And, just for the fun of it, I am also going to read the article.

Kindly,
Simon
