### ISSUE TITLE
Service labels not initialized properly

### ISSUE THREAD

**Issue by remark84** [meetfranz/franz#32]
When you add a service it asks for a name, but there is no place that displays the name of that particular service.

If you have a name for a service at the least provide a tooltip for the name of that service.

Right now, it just shows an icon of the current services ie gmail, messenger whatever. 
One of the reasons I use Franz is because it allows multiple instances of hotmail or gmail, but I need a label to differentiate them. 

I'm using Windows 10 Professional x64

**Comment by adlk** [comment]
There is a tooltip when hovering but it seems like it's not always initialized properly.
<img width="190" alt="tooltip" src="https://user-images.githubusercontent.com/3265004/31789052-12f70456-b511-11e7-87d8-d76e3d241cd0.png">

**Comment by arsyan** [comment]
hi, im a premium paid user.

i would like this option to be available where the account change are horizontally laid out.
make an option for users to choose between the two, for a UMPC user, vertical real estate is important. 

I hope u can add this feature again so we can change it to horizontal layout for all the services instead of vertical.

**Comment by adlk** [comment]
@arsyan don't worry, it's on my list :)

**Comment by remark84** [comment]
Awesome, it sounds like you have it covered then. I definitely am having initialization issues with the tooltips. I would just prefer to be able to see the label.
