### ISSUE TITLE
Incorrect WhatsApp notifications count

### ISSUE THREAD

**Issue by AGonLen** [meetfranz/franz#343]
As you can see in the screenshots attached below, although I have 4 unread messages (2 on each chat) the application only shows 2 unread messages (1 per chat), and the overall notification in the taskbar only counts 3, being: 2 (WhatsApp)+1 (GMail).

Franz Version used: 5.0.0.beta.14
Operating System and version: Windows 10 Pro Fall Creators Update

![franzissue2](https://user-images.githubusercontent.com/24992203/33215697-eca75cba-d130-11e7-8314-cc980a7a1d9e.JPG)

![franzissue1](https://user-images.githubusercontent.com/24992203/33215686-dfa835c0-d130-11e7-8e9e-55bc9df8524b.JPG)

**Comment by adlk** [comment]
Franz usually counts and show unread message threads instead of unread messages. 

I've made this decision with a scenario of having 5-10 active services in mind. If there is a huge conversation going on in one or two channels – chances are pretty high that you are being greeted by a _60 unread messages_-badge. IMO this is creating stress instead of enhancing productivity.
