### ISSUE TITLE
GMAIL verification 

### ISSUE THREAD

**Issue by linux923344** [meetfranz/franz#372]
Hello!  
When I log in and i want to give my verification code by sms the page is isnt loading :(

I tried also reinstall and reboot system. Nothing :(

### Screenshots (if appropriate):
https://mega.nz/#!lGQSGAKA!yzdy50BdDJ2JqDDPsy5De08bzDhJCozjlnpOoIvHly4

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Kubuntu 17.10 64-Bit Kernel 4.13.0-17-generic,

EDIT:
Also not working Google Keep and Calendar

**Comment by AGonLen** [comment]
Yep, I had the same thing, with the 2 steps verification, when doing it with the "Yes"/"No" allow connection from the mobile.
Then in order to make it work had to do the 2 steps verification with just an authorization code...

Franz Version used when wrote message: 5.0.0.beta.14
Operating System and version: Windows 10 Pro Fall Creators Update

**Comment by BrianGilbert** [comment]
Please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins
