### ISSUE TITLE
Slack: Multiple Workspaces

### ISSUE THREAD

**Issue by marcobiedermann** [meetfranz/franz#391]
### Expected Behavior
Add multiple workspaces and switch between them

### Current Behavior
Only one workspace per service.
If you try to add another workspace, your browser will open and you can only login into the web version of Slack

### Your Environment
* Franz Version used: Franz 4 & 5
* Operating System and version: macOS 10.13

**Comment by vibhas77** [comment]
It is more likely to be a feature than a bug.. It would be easier to manage notifications if each workspace has it's own service.

**Comment by Joejoboi** [comment]
I'm able to have multiple Slack workspaces. I have no idea why that might be. I find your described current behavior happening when I try to download an time from Slack.

**Comment by adlk** [comment]
The way how Franz was designed is that one Slack workspace equals one service in Franz. Instead of adding a workspace via the Slack menu you need the service via the Franz settings.

**Comment by marcobiedermann** [comment]
Hmm, okay. Thank you for your quick reply. Not the most elegant solution, I think but it would work.
Wouldn‘t this be considered a new feature to Franz?

**Comment by alecive** [comment]
There is no point in having this feature in franz. You can have multiple workspaces available (and loaded, which is a big point with slack since it is very slow to load in the beginning) at the same time, no need to switch in some clunky way, and so on. If you like the multiple workspace approach, the slack app does that pretty good so there would not even be the need to switch to franz in the first place.

**Comment by marcobiedermann** [comment]
Okay, thank you for explaining :)

**Comment by MartyMaro** [comment]
@alecive Sorry, I don't want to open this, as I know the issue is on the side of Slack. They solved it in their own app, but not on their website. This can be no solution now. The whole point in using multiple messages in one is too get rid of the "one app per service" madness that Franz tries to solve. 

Ofc, it would be nice to have a feature that works like the Slack app's feature, but I think the whole problem is that the website itself does not allow this. I doubt they will change anything about it, though.

**Comment by zoltansn** [comment]
I am trying to do this with Gmail and genuinely don't understand the explanation. I've read other threads too, like #618 where @alecive says "You just need to open multiple recipes within franz " - what are "multiple recipes" and how do I "just open" them???

**Comment by GillesVercammen** [comment]
@zoltansn I think he means that you need to add another gmail service (the + icon in the tabbar).
So you have an icon in your tabbar for each email account.

The advantage also is that both email inboxes are always loaded. So you don't even have to switch between them. 

For easier use you can give the services your own chosen icon (to distinguish both email maybe)
when you added the 2nd email service, click that icon and log in with your 2nd email.

I hope this is clear for you.

**Comment by zoltansn** [comment]
@GillesVercammen thank you, alas I've already tried that. It will only allow me to change the existing Gmail service, in other words I can't seem to have 2 of the same services. Is that a premium feature perhaps? Maybe this helps, here is what I did:

1. open Franz
2. click Add new service (+ sign on the bottom left)
3. from Available services select Gmail
4. highlighted menu item changes from Available services to Your services (!)
5. I can then change name, icon etc. BUT that will change the settings to the Gmail service that is already there rather than creating a new one.

Any ideaZ?
