### ISSUE TITLE
Feature request: Bring back the service on/off switcher

### ISSUE THREAD

**Issue by brendanjones** [meetfranz/franz#449]
*Darth Vader voice* Nooooooooooo

What happened to the dropdown service on/off switcher from 4.x.x? It was my favourite feature compared to Rambox :'(

Now you have to right-click on each service individually and find the enable/disable option. What if you want to enable/disable a couple at once? It's quite laborious. 

Essential features shouldn't have to be accidentally discovered/accessed by right-clicking.

You could put another icon above the disable audio bell icon.

**Comment by brendanjones** [comment]
This could be bundled with ##344. Under the one popup window, place an on/off 'disable all notifications' slider at the top, and then list all available services under that, each with the on/off slider.

**Comment by adlk** [comment]
Most of the features of Franz 4 will be added in v5 again. I'm currently just doing a lot of prioritization juggling as this feature was indeed handy but wasn't used that much compared to other things. – Having said all this, it will come again ;)

**Comment by brendanjones** [comment]
I'm curious, how do you know it wasn't used that much?

**Comment by adlk** [comment]
Google Analytics events

**Comment by Maxincredible52** [comment]
i think this is the kind of feature that isn't used much in analytics events but it will deter the most hardcore users because they especially need that feature (me) ^^ 

know that myself as i work in a start up company where features oftentimes are rushed or taken in/out quickly. 

In my special usecase i only need the feature on my laptop that does not have a lot of RAM (8GB) which is not much when you are trying to develop stuff. When i am @ work I could quickly disable my private messaging services to save up some RAM and it really helps!

Props to you that you will bring it back!

**Comment by haraldox** [comment]
this is implemented again in the latest version of Franz 5.0.0-beta.15! :) closing this
