### ISSUE TITLE
Should open main window when clicking on native notification popup

### ISSUE THREAD

**Issue by theosophist123** [meetfranz/franz#453]
### Expected Behavior

Franz should open its main window when click on message notification popup.
Preferably into conversation to which the message is related.

### Current Behavior

Doesn't react to any click

**Comment by adlk** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

**Comment by Sophia10** [comment]
I have the same issue.

### Expected Behavior
Upon clicking on the notification, Franz should open in the conversation that has a new message. It would be great if this was optional (I know people who don't like the app to open and want to get rid of the notification popup quickly).

### Current Behavior
When clicking on a notification, nothing happens.

### Steps to Reproduce (for bugs)
1. Get a new message.
2. Click on the notification pop-up.
3. Wait and nothing will happen.

### Context
For answering messages faster, it would be very helpful to automatically open Franz when I click on the notification. As far as I remember that worked in Franz 4 but it didn't lead you to the updated conversation.

### Your Environment
* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 8.1

**Comment by haraldox** [comment]
@theosophist123 what OS and version are you on?

seems to work on macOS

**Comment by theosophist123** [comment]
Im on ubuntu 17.10
