### ISSUE TITLE
Auto-Restart after version update shows a blank window with no services

### ISSUE THREAD

**Issue by tofi86** [meetfranz/franz#580]
### Expected Behavior
* update Franz via the blue footer banner update notification
* app restarts automatically with all previously used services

### Current Behavior
* update Franz via the blue footer banner update notification
* app restarts automatically with an empty GUI with no services
* close and restart Franz manually
* all services are back

that's quite confusing...

### Screenshots (if appropriate):
* missed the opportunity

### Steps to Reproduce (for bugs)

1. see above
2.
3.
4.

### Your Environment

* Franz Version used: upgrade from last version to 5.0.0-beta15.607
* Operating System and version: macOS 10.13.2

**Comment by tofi86** [comment]
#575

**Comment by haraldox** [comment]
maybe also related to #528

**Comment by haraldox** [comment]
closing this since it worked after closing and restarting Franz manually

**Comment by tofi86** [comment]
lol, that's your solution?! not very UX friendly 😭

What happens if the user doesn't restart and instead angrily adds all his services manually before doing a restart?
I haven't tried, but a) it's a waste of time because of bad UX design and b) probably adds all services as duplicates to the franz account...

**Comment by tofi86** [comment]
> maybe also related to #528

looking at the screenshot in #528 I can tell that it wasn't a "bluescreen" what showed up after updating. it was the standard GUI (grey) but with no services...

**Comment by haraldox** [comment]
@tofi86 you're right, reopening ... anyone else experiencing this issue? it's hard to reproduce...

**Comment by TobiasFeld** [comment]
I've got the same issue on Windows 8.1
But instead of adding services again or restart. I tried logout/login.
Can't login "Email or password not valid" and on password reset (with same email as i tried to login), i am getting "Please check your email" but not mail received.

**Comment by Lm0490** [comment]
I have the same issue but neither a logout nor a restart of franz changes it. also i cannot add services manually - I am using Version 5.0.0-beta.15 (5.0.0-beta.15.607) on a Mac (10.13.2 (17C205)).

**Comment by TobiasFeld** [comment]
**Update**

Found a way to get it working on windows again. 

1. Uninstall Franz 
2. Remove (by hand) Franz folders from User> AppData > Local (and/or Roaming).
3. Install Franz again and login

Found my correct Password luckily - Password reset still not working

**Comment by brendanjones** [comment]
I have a similar bug on MacOS. Suspect it's related so won't create an extra issue:

After computer sleep, and Franz was already open before the sleep, any services that were activated display a blank grey window.
- The service appears to be active, because the service icon is coloured
- Refreshing the service activates it again
- Any services that weren't active activate just fine, this issue is only for services that were active already before the computer was put to sleep.
- This is not service specific, because it happened to all my different active services.

Example screenshot of 'inactive' active service:

![screen shot 2018-01-17 at 3 05 37 pm](https://user-images.githubusercontent.com/16049594/35046657-ef6747e4-fb97-11e7-9c4f-cae3414c40a6.png)

**Comment by tofi86** [comment]
in my case (original issue) the service bar to the left was completely empty after the auto upgrade.

so @brendanjones's issue is probably not related...

**Comment by brendanjones** [comment]
Ah, in that case I'll make a separate issue.

**Comment by haraldox** [comment]
@brendanjones thanks!
