### ISSUE TITLE
Problem to log in on Slack using Franz

### ISSUE THREAD

**Issue by patsi9** [meetfranz/franz#652]
I tried to add a new service of Slack on Franz and the page appears blank and doesn't have the place to log in. What shall I do?

**Comment by haraldox** [comment]
Can you please update your initial issue with all the necessary information like macOS version, exact Franz version and so on. Please use this [template](https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md), it makes tracking and reproducing issues much easier.

**Comment by santialbo** [comment]
The same happens to me







### Expected Behavior



### Current Behavior
Slack doesn't load when added as a service. Tried readding, `Ctrl-R`, restarting the app, etc.



### Screenshots (if appropriate):
![screenshot](https://i.imgur.com/VuqbqF4.png)

### Possible Solution



### Steps to Reproduce (for bugs)


1.
2.
3.
4.

### Context



### Your Environment

* Franz Version used: 5.0.0-beta.15
* Operating System and version: Windows

**Comment by santialbo** [comment]
Solved. I was missing the team on the service settings page.

**Comment by ninhnv-runsystem** [comment]
oh, i got same problem. Just restart `Franz`

**Comment by nunogoncalves** [comment]
Our team as ADFS login system. And I can't ever use this team in Franz. That's very unfortunate. :(
