### ISSUE TITLE
Empty bluescreen window on Ubuntu 17.10

### ISSUE THREAD

**Issue by tienhuynh5312** [meetfranz/franz#674]
After installing Franz 5.0.15 beta on Ubuntu 17.10, it stucks at blue empty windows.

**Comment by jay-hankins** [comment]
I am also seeing this on mac OS High Sierra 10.13.3. It routinely happens when I'm connected to my own VPN server. As soon as I disconnect, Franz is able to load. Then, I can re-enable the VPN and go about using Franz. Quite strange.

![2018-02-12 09 33 34](https://user-images.githubusercontent.com/8591383/36101748-3a76555a-0fd8-11e8-85c4-87304f0572a5.gif)

**Comment by tienhuynh5312** [comment]
@jay-hankins I think there is a problem with Franz DNS. I figured out that I also used pihole to block ads, so the pihole could have been blocked franz dns request. You VPN services could not resolve or block those DNS.

**Comment by jay-hankins** [comment]
Good call-- I'm also using Pihole in my network which I'm VPNed to.

**Comment by jay-hankins** [comment]
Update: I had to whitelist `www-google-analytics.l.google.com` in Pihole. I think Franz should be able to function with Google Analytics blocked, but that is a workaround for now.

**Comment by AgusNahas** [comment]
Hi! I'm having the same issue, Win10. I tried uninstalling and installing again and it didn't work.
Also I tried installing beta 5.2.1. Still the same.

Any clues?  

I don't know if it helps, but in Win10, it keeps showing the message 'Windows 7 and above is required' if I don't run the installer as administrator.
