### ISSUE TITLE
Unable to Authenticate Microsoft Teams External Apps

### ISSUE THREAD

**Issue by Pylawn** [meetfranz/franz#684]
### Expected Behavior

When attempting to connect an external service in Microsoft Teams such as Jira Cloud, clicking the authentication button should open a popup window asking the user to sign into their Jira Cloud account. This is what happens in the browser version of Teams.

### Current Behavior

When you click the link to login to the service (In this case Jira for Teams) nothing happens.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/36481559/36212830-011e4b40-1173-11e8-8db7-d6b2214e9339.png)

### Steps to Reproduce (for bugs)

1. Click the ... on the left menu in teams
2. Add the Jira Cloud Service
3. Attempt to sign in to the service
4.

### Your Environment

* Franz Version used:
Attempted Most recent version and Beta
* Operating System and version:
Windows 10 Creators Update

**Comment by brandonh-msft** [comment]
Akin to this issue is that of certificate (Windows Hello) authentication prompt for **any** Organization-based (eg: Office 365) Microsoft login. In these scenarios, an _OS-level_ flow is kicked off to select the certificate to use for authentication, or go through the Windows Hello authentication flow. In cases where this is attempted, no popup/auth flow is ever seen. Users simply sit at

![image](https://user-images.githubusercontent.com/20270743/50782466-ef254880-125c-11e9-8e57-c0205edd8aad.png)

and never get the opportunity to auth.

**Comment by l-Marty-l** [comment]
I can confirm this issue is still relevant and it makes Teams unusable for me. Teams strength in opposition to other services is to have many external apps, but authorization within Franz is impossible. The free plan of Teams has no tasks, so external apps like Trello are mandatory to beat competition.

A solution would be to let the Chromium container allow to open popup windows.

**Comment by bc3tech** [comment]
It's curious to me this doesn't work; I can double-click a message in the Outlook 365 service and it pops up a new window just fine. 🤷‍♂️

**Comment by bc3tech** [comment]
![](https://media1.tenor.com/images/d47da480fc70446a3390d370f2994b05/tenor.gif?itemid=5604237)
