### ISSUE TITLE
Links won't open 

### ISSUE THREAD

**Issue by jcpelizzon** [meetfranz/franz#690]
Whenever I click on a link in Slack it just opens a new window and not the actual link. 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by Grsmto** [comment]
I don't think this is related to Franz. It's happening to me since yesterday on Slack standalone app as well. Maybe a Chrome issue?

**Comment by clasig** [comment]
This is still happening

**### Expected Behavior:** 
Clicking on a link inside Franz, you should be redirected to your browser in which the link is opened

**### Current Behavior:** 
Clicking on a link inside Franz, redirects you to your browser but does not open the url, neither generates a new tab.

**### Context**
I tried this from gmail, slack, whatsapp and facebook messenger, same issue

### **Franz Version used:**
Versión 5.0.0-beta.18 (5.0.0-beta.18.903)

### **Operating System and version:**
iOS Mohave 10.14
