### ISSUE TITLE
Cannot Make Skype Voice or Video Calls

### ISSUE THREAD

**Issue by jumipi** [meetfranz/franz#703]
Although chat feature is working perfectly, the Video Calls and Voice Calls icons are grayed out and unusable. I am using the latest version of Franz 5.0.0-beta.14 on Windows 10 desktop computer.

Also, since downloading and installing Franz, my regular Skype app no longer allows me to sign in. Do you know why this is?

**Comment by wingsofovnia** [comment]
Same here!

**Comment by Beatfry** [comment]
Same here!

**Comment by john-shipp** [comment]
I too am having this issue running Mac OSX Franz 5.0.0-beta.16 (5.0.0-beta.16.762)

**Comment by flrizzato** [comment]
Same here!

**Comment by ljavierrivera** [comment]
Ditto!

**Comment by blis5fool** [comment]
Looks like voice and video calls are only available from Chrome or Edge:
https://support.skype.com/en/faq/FA34515/finding-your-way-around-skype-for-web-and-outlook-com

> How do I make a voice or video call?
> 
> To enjoy Skype voice and video calls with your contacts in Outlook.com, you need to use Microsoft Edge and latest versions of Chrome.
> 
> If you receive the message "Audio and video calls are not supported on your browser", be sure you are using Chrome or Edge.

**Comment by jumipi** [comment]
I don’t know what you are talking about – I clearly said from the Franz app NOT a browser.

**Comment by blis5fool** [comment]
Um. Franz app is just another browser. It's internally using Chromium version 59. It's just rendering the webpage inside it. That's why Skype "service" from Franz app will look exactly the same if you go to [Skype for Web](https://web.skype.com) service (URL: https://web.skype.com) in a browser like Chrome or Firefox.

"Skype for Web" will recognize this as not accessing it from Chrome or Edge and will deactivate the Voice/Video calling feature.

**Comment by blis5fool** [comment]
I've found another similar app [(Station)](https://getstation.com) that uses Chrome version 61 and voice/video calling button is active (haven't actually tried it) so it might be just that Franz is using unsupported version of Chrome. Or, it might be that Station did extra work to make it work it's being actively worked on.

**Comment by SeeJayDee** [comment]
Can confirm this issue is still occurring on 5.0.0-beta.18

**Comment by brucej72** [comment]
Yes, this still does not work on 5.0.0-beta.22 (5.0.0-beta.22.1059). In Skype, the call button is greyed out for all contacts, while the video call is not, but does not work when you click it (i.e. nothing happens)

**Comment by brucej72** [comment]
@adlk I think this issue needs to be reopened

**Comment by brucej72** [comment]
![screenshot 2019-01-29 at 14 38 24](https://user-images.githubusercontent.com/6052403/51915974-36be7080-23d4-11e9-869b-1c956ee2fcbe.png)
See image attached showing "real" Skype desktop app in foreground with call button enabled, and Franz window behind with the call button disabled.

**Comment by tresloukadu** [comment]
same here

**Comment by zeshanmusawar** [comment]
I would advise you to delete the Skype app, update your Mac OS X to 10.13.4 and reinstall the app > https://www.skype.com/en/get-skype/ > Get Skype for Mac 
If it doesn't help, write me back

**Comment by jumipi** [comment]
I have a dell pc, not a MAC also there is no issue with the Skype app, its with Franz

 

Justin Pinkus

p/c: 631.294.3327

Skype: justin.pinkus1

 <mailto:justinpinkus@gmail.com> justinpinkus@gmail.com

 

LinkedIn:  <https://www.linkedin.com/in/justinpinkus> https://www.linkedin.com/in/justinpinkus

**Comment by blis5fool** [comment]
As I've mentioned earlier, Franz, as well as other similar apps like Station and Shift, are all just custom browsers and they all use the web version of skype -- https://web.skype.com

I've also mentioned that the call button is enabled in Station, even though they use the same web app but they were using chrome version 61 as oppose to version 59 used by Franz. It looks like Franz is now using version 69 (Station is currently using version 66) but it's still not working. See my screenshot here for the chrome version used by Franz:
https://imgur.com/a/uz67wGa

I'm not sure what Station is doing different to have the call button enabled. It doesn't seem like they are modifying the user-agent... maybe they are not being flagged as non-chrome browser because they are not as popular as Franz?

By the way, if you open the web app in Firefox or Opera, the call button will also be disabled.

**Comment by brucej72** [comment]
The plugins can set the user agent, but in the skype case this isn't done. I'm not sure where the default comes from or what it's set to.

**Comment by lgladysz** [comment]
Franz needs to set the user agent to Edge in MS Teams to make video and audio calls.

**Comment by zazoomauro** [comment]
👍
