### ISSUE TITLE
Images sent via skype don't open

### ISSUE THREAD

**Issue by divory** [meetfranz/franz#739]
When you click on an image sent to you via Skype it should open. However, the link doesn't work.
I've tried multiple images. 

Link: https://api.asm.skype.com/v1/objects/0-neu-d3-92f8a7107347f584ab65f83a42f5f521/views/imgpsh_fullsize 

Using Windows 10. Franz 5 

Thanks!

**Comment by john-shipp** [comment]
I am too having this issue running Mac OSX (high sierra) Franz 5.

Thank you!

**Comment by WPUtvecklare** [comment]
I'm having the same issue. Mac OSX High Sierra with Franz 5.

**Comment by Virtuaalivaluutta** [comment]
Yep same issue. Using the new Macbook pro.

**Comment by jwbambacht** [comment]
MacOs, same issue. Have to open the Skype application next to it if i want to view the image...

**Comment by felipegreg** [comment]
Same issue (Windows 10 x64 / Franz 5)

**Comment by Karan1458** [comment]
Same issue Win 10

**Comment by gytiskv** [comment]
Same issue.
macOS High Sierra 10.13.14
Franz 5.0.0-beta.18

**Comment by samuelfvlcastro** [comment]
Same issue
macOS High Sierra 10.13.14
Version 5.0.0-beta.18 (5.0.0-beta.18.903)

**Comment by georgecarstoiu** [comment]
Having same issue.

Win10 64bit
Version 5.0.0-beta.18
Release 1.8.4

**Comment by zanvd** [comment]
Also on the Linux version of Franz:
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

As proposed by George, this is most likely an authorization problem when creating the request.

**Comment by kelvinau** [comment]
same issue.
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64
Rambox doesn't have this issue.

**Comment by QuanTran91** [comment]
Same issue.
I think you take see how Rambox implement it.

**Comment by kelvinau** [comment]
I have a fix for a solution for this issue:

It is because images sent in Skype require authentication to be viewed, and Skype uses the cookie named `skypetoken_asm` under the url `https://api.asm.skype.com`, and this cookie is HTTPOnly.

The simplest way to fix it is using BrowserWindow to open another window, which can carry the same cookies from the current session, and loads that URL in.

Submitted a PR: https://github.com/meetfranz/recipe-skype/pull/14

(For how to deploy the skype recipe, the documentation is located here https://github.com/meetfranz/plugins/blob/master/docs/integration.md)
