### ISSUE TITLE
Minimize to system tray option

### ISSUE THREAD

**Issue by afonsojramos** [meetfranz/franz#763]
Minimize to system tray option does not have the expected behavior.

### Expected Behavior
**Minimize to system tray** option **enabled**: 

- Clicks close : goes to **system tray**.

- Clicks minimize : goes to **taskbar**.

**Minimize to system tray** option **disabled**: 

- Clicks close : **Quit Franz**.

- Clicks minimize : goes to **taskbar**.

### Current Behavior
**Minimize to system tray** option **enabled**: 

- Clicks close : goes to system tray.

- Clicks minimize : goes to system tray.

**Minimize to system tray** option **disabled**: 

- Clicks close : goes to taskbar.

- Clicks minimize : goes to taskbar.

### Context
I think the current implementation is a little obnoxious

### Your Environment
* Franz Version used:5.0.0-Beta.16
* Operating System and version: Windows 10, however I haven't evaluated the Linux version if the behavior is the same.

**Comment by closingin** [comment]
Why would you want to put the app in the taskbar on minimize if "minimize to system tray" is enabled ? That makes no sense at all.

**Comment by imaginarny** [comment]
I think it's not designed very well since beginning which in fact prevents me from using Franz, sadly. I agree what @AJRamos308 says doesn't make sense. But surely, Franz doesn't behave like apps usually on systems do. I would suggest following:

* **"Keep Franz in background when closing the window"** option should affect closing functionality only. Franz on close should close window. If it's not checked, it should quit the app. Straightforward.
* **"Minimize Franz to system tray"** option should affect minimize functionality only. In the end, it literally says that by checking this, you disable default window minimization to taskbar / dock.

**Problem:** minimization option affects also closing. Which is prevented **when it is checked**. So when you want to retain minimization to taskbar, **you can't close window anymore**.

Therefore, with options combination like this, you can't have both minimize to taskbar / dock and close functionality at the same time.

**Solution:** **"Minimize Franz to system tray"** should not affect close functionality.

I would suggest to raise priority of this issue as it breaks default system behavior / functionality.
It looks like issue #468 is about the very same problem, but I don't think another option is needed and also it should not be marked as a feature request then, from system view it's more like a bug. Right functionality should be achieved with offered solution. What do you think?

**Comment by imaginarny** [comment]
@closingin it would be great. I agree that devs and other users should look at this, in fact it could save time implementing other already submitted feature requests which won't make sense if options behaved like described. Thanks for reply, will wait.

**Comment by imaginarny** [comment]
Few months past, another related issue to this settings flaw. #1006
