### ISSUE TITLE
account password requirements

### ISSUE THREAD

**Issue by Stanzilla** [meetfranz/franz#768]
Currently Franz accounts have a max password length of 25, any reason why? Can this be changed?

**Comment by vendforce** [comment]
where you ever in the  gestapo ?? 

who could ever want to use a 25 char password ?? thats just nuts .. and really excessive and just over kill, and actually less secure if you are using a long password with lowercase instead of  a 12 char password , upper and lower case , numbers and characters it would take a couple of years to crack and.. your not that important snowflake . the chinese have better uses for there computers than seeing your chats 

there is easier ways to gain acess to a system like looking for flaws in sql and xml , and social engineering.. hackers dont just try to bruteforce passwords 

anything over 12 char with numbers,caps,lowercase and characters is strong enough

**Comment by Stanzilla** [comment]
@adlk veto!
