### ISSUE TITLE
LINE integration

### ISSUE THREAD

**Issue by haruspazer** [meetfranz/franz#795]
I think LINE would come great for Franz.

**Comment by Amandaville** [comment]
Agreed, I need LINE integration for Franz to be an ALL-IN-ONE messaging solution.  Besides, LINE has over 33,000,000 active users monthly.

**Comment by koma-private** [comment]
Agreed too. But we have big problem integrating LINE to Franz.
I also posted same message to #service on Franz' Slack as below:

> I tried to make recipe for LINE before, but unfortunately LINE doesn’t provide web access and cannot login from Franz. Users have to install a Chrome App for LINE to use this service from browser, but in my understanding, "electron", which used as a browsing engine of Franz supports neither Chrome Apps nor Chrome extensions.
>
> On the other hand, Official Chromium blog says they will remove support for Chrome Apps (https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html?m=1)
So, I’m watching LINE’s action whether they will continue supporting web access by replacing the Chrome App with some open technology or not.
If LINE will replace their proprietary Chrome App with common browser web API, then there will be a chance for a Franz recipe to login

Conclusion:
Please wait for LINE's decision

**Comment by silud** [comment]
How about using the Chrome extension: https://chrome.google.com/webstore/detail/line/menkifleemblimdogmoihpfopnplikde?hl=en

**Comment by rastarr** [comment]
thanks for the update - would love LINE also. Running multiple accounts in VMs is quite painful ^_^

**Comment by BerndErnst** [comment]
Hows the status? @koma-private

**Comment by koma-private** [comment]
@BerndErnst 
I have not seen any LINE's official announcement yet that they have plan to replace a web interface to their service with common web technologies.
For recent updates, you should check their tweets here. https://twitter.com/line_global

**Comment by robert1112** [comment]
+1 Hi Is there any update on this? Thank you.

**Comment by robert1112** [comment]
> Agreed too. But we have big problem integrating LINE to Franz.
> I also posted same message to #service on Franz' Slack as below:
> 
> > I tried to make recipe for LINE before, but unfortunately LINE doesn’t provide web access and cannot login from Franz. Users have to install a Chrome App for LINE to use this service from browser, but in my understanding, "electron", which used as a browsing engine of Franz supports neither Chrome Apps nor Chrome extensions.
> > On the other hand, Official Chromium blog says they will remove support for Chrome Apps (https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html?m=1)
> > So, I’m watching LINE’s action whether they will continue supporting web access by replacing the Chrome App with some open technology or not.
> > If LINE will replace their proprietary Chrome App with common browser web API, then there will be a chance for a Franz recipe to login
> 
> Conclusion:
> Please wait for LINE's decision

Hi @koma-private

But I saw others can do just it. Here is the link. Can you kindly help? Thanks.
https://www.easychat.co/integrate/line.html

**Comment by koma-private** [comment]
Hi @robert1112 

Thanks for sharing interesting info. That page explains how to integrate EasyChat with LINE@ (LINE service for business)

However, I think this is off-topic for 2 reasons.

1. In my understanding, LINE@ is like a chat bot service and not intended to be used by end users. we should consider LINE and LINE@ (aka LINE for business) separately. 

2. According to that page, LINE@ offers Webhook service which we can receive JSON data via Messaging API. But JSON is just a text data and you need to write codes for implementing chat console to parse received messages like as EasyChat.  Besides, you also have to write and run programs to accept Webhooks on some hosting server.

Since Franz recipe is designed to work as a simple "proxy" between messaging service and Franz,  as far as I know most of recipes are just counting unread messages by accessing DOM and passing value to Franz to show "unread number badge" on its icon. Nothing more and nothing less. So, I think this topic is beyond the scope of Franz recipe.

**Comment by robert1112** [comment]
Hi @koma-private 

Thanks for your reply. 

1.  LINE@ has chat bot but it is also like a regular line chat. Line@ is paid account. Regular LINE is free. In the link below, it seems only LINE@ can be integrated. (because web hook is available and open?)
https://help.crisp.chat/en/article/how-to-link-crisp-with-line-1gz50s7/

2. I am not a technical person. Sorry.

After viewing the link above, do you think LINE and LINE@ are both not possible with Franz? Thank you.

**Comment by koma-private** [comment]
Hi @robert1112

> because web hook is available and open?
I think so. According to this document, Web hook is available only for LINE@
https://developers.line.biz/en/docs/messaging-api/overview/

> do you think LINE and LINE@ are both not possible with Franz?
Unfortunately, yes. Franz is just a browser, not a messaging platform like EasyChat, Crisp. So if you could access LINE by using normal Chrome without any extensions, you could  access it from Franz too. Or, please consider to use EasyChat, Crisp or whatever you can integrate them with LINE@ web hooks. Then, access them from Franz.

**Comment by robert1112** [comment]
Thank you for everything and your hard work.

**Comment by jscw82** [comment]
I came across this official extension by Line for Chrome.
https://chrome.google.com/webstore/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc

Wondering if it is something that can be used to come up with a quick workaround?
