### ISSUE TITLE
Add a mute notification button 

### ISSUE THREAD

**Issue by tobiasdueser** [meetfranz/franz#8]
### Feature Description

Add a button in the sidebar (and a shortcut) to disable/mute all notifications temporarily. Hide all notification badges and disable the sound from the services (didn't work in older versions).

**Comment by jpmello** [comment]
PLEASE! WE have this in the previous version and in the new one (5) we don't, this feature is very important :( 

I've 5 services connected, it drives me crazy to receive all those sound notifications and push.

**Comment by zeemawn** [comment]
is it possible at all to mute services at the moment? Haven't found any setting in the app

**Comment by Wouter0100** [comment]
Used this feature from time-to-time myself. Not as a daily thing, but would be useful to have this back again.

**Comment by hmalaud** [comment]
Would really be useful to have that back.

**Comment by HanatielHawk** [comment]
I would like to stress the importance of this function. Then again the previous version showed Windows notifications and the 5.0.0 just shows a notification in the notification bar and not the action center.

I would like to see this functionality being brought back: option to disable all notifications; Windows toasts when receiving a notification from an app (such as WhatsApp).

**Comment by tobiasdueser** [comment]
I made a mockup for a "mute sound"/"mute notification" button: 

![image](https://user-images.githubusercontent.com/1573849/32442743-c156f72e-c2fc-11e7-9044-7eea8e4afdeb.png)

![image](https://user-images.githubusercontent.com/1573849/32442739-baa25a72-c2fc-11e7-9b49-ee1edbe66bfa.png)

**Comment by alecive** [comment]
That is definitely a much cleaner and consistent design! I like the second more though.

**Comment by adlk** [comment]
Most critical question, ever: Where do we put the Franz logo? 😁

**Comment by alecive** [comment]
Good point. Maybe you can add the logo at the very bottom that opens some window like "about franz", and then on top of it the settings and mute icons.

What I really don't like is having all of these nice icons without text and then the text below the franz logo because it's difficult for an user to understand that that icon is the settings icon.

**Comment by HanatielHawk** [comment]
It's starting to get really annoying now. Even when I have Windows 10 quiet hours enabled and turned the notifications for each service off, I still get notifications from Messenger and Whatsapp. I've decided to roll back to Franz 4.0.4 until the mute function is restored, because using the new versions causes too much of an intervention on my day to day work, while this function works perfectly in Franz 4.0.4.

**Comment by tobiasdueser** [comment]
@adlk I thought that you want to keep the logo, buuut do we really need it? 🙈  I can't think of one mac app that has a logo in the UI. It is still highly visible in the dock and app switcher (at least on mac).

**Comment by adlk** [comment]
@tobiasdueser No actually not. I‘ve thought about that for a while and I really like the mockup. I will do a first test in b14.

**Comment by johangu** [comment]
Please just make it mute notifications sound, *not* all sound as in previous version of Franz, it's incredibly annoying to not be able to just get rid of that annoying notification beep, without losing the ability to listen to e.g. WhatsApp voice messages.

**Comment by adlk** [comment]
@johangu While this is not a perfect solution, just disabling the services notification sound is not feasible at the current state.
While it is technically possible to fake an audio API and just filter certain audio files – a solution like this is so extremely error prone, especially with 3rd party recipe authors.

All in all, I wanted to have a better solution before adding this feature but there is a huge amount of requests to re-add this and we've made a quite good experience with this solution in the past.

---

I'm closing this issue as the initial feature request is ready for shipping. I'd suggest to open a new issue where we can discuss possible solutions for _just_ disabling notifications sounds instead of muting the whole webview.
