### ISSUE TITLE
Windows: Disabling notifications is not saved

### ISSUE THREAD

**Issue by stefahn** [meetfranz/franz#803]
Disabling notifications and sound works well in Windows 10 (in contrast to MacOS as I read). However if my notebooks comes back from energy saving mode (or shutdown) notifications are enabled again. So the disabling is not saved.

Would be nice if Franz remembered this setting.

Using 5.0.0-beta.16, Windows 10 64 bit.

**Comment by adlk** [comment]
Are you talking about this option here? 
<img width="69" alt="bildschirmfoto 2018-03-18 um 16 02 58" src="https://user-images.githubusercontent.com/3265004/37567343-f4702640-2ac5-11e8-95cf-7c272983b984.png">

It was actually designed to be a session based option especially since the systems DND mode controls this until the user decides to override the current system state. Overall, I'm not very happy with how mute works and is perceived by users as it is actually a complex option with a lot of side effects.

**Comment by stefahn** [comment]
Hello Stefan, 

yes, I mean that option. If I remember correctly, the old Franz remembered the mute state. 

For me mute is essential since I don't want to be distracted by new messenger messages - but don't want to close/open Franz all the time either.
