### ISSUE TITLE
Franz 5.0.0. beta drives my MBP fans mad

### ISSUE THREAD

**Issue by sublabat** [meetfranz/franz#850]
franz 5.0.0. beta drives my 2015er retina mbp fans mad.
has anybody a similiar issue?

**Comment by rygos** [comment]
For me the same.

Franz 5.0.0-beta.17.834
macOS 10.13.4 Beta(17E197a)

Running Services with Franz: WhatsApp, Telegram, Discord, Github, Skype and Riot.

CPU load of Franz: 20% the whole time its open. some peaks above if I switch services.

**Comment by pdellaert** [comment]
I'm still seeing this issue. 

Mac OS 10.14 (18A391), 3.1 GHz Intel Core i7, 16 GB 1867 MHz DDR3
Franz 5.0.0-beta.24.1110

CPU usage from activity monitor:
Franz Helper: 52.5%
Franz Helper: 29.2%
Franz: 27.8%
Franz Helper: 26.3%
Franz Helper: 18.2%

Services used: 
Messenger, WhatsApp, 4x Slack

It basically overloads my whole system, blocking almost any action, slowing down all programs. Franz has become useless for me, because of this...
