### ISSUE TITLE
Can't Quit Franz from Menu

### ISSUE THREAD

**Issue by anthonyg2003** [meetfranz/franz#902]
### Expected Behavior
From menu bar, when going to File --> Quit, I expect the Franz program to quit entirely.

### Current Behavior
When I go to File --> Quit, nothing happens. Doesn't quit Franz, doesn't minimize, nothing.

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/19936471/38899918-ba92fc88-4256-11e8-865f-d1837378e0b4.png)

### Steps to Reproduce (for bugs)
1.  Go to Menu, click File
2. Click Quit

### Context
I've noticed this in the past week, but maybe it's been happening for longer

### Your Environment
Franz version 5.0.0-beta.18
Windows 10 Enterprise, 64 Bit

Franz Settings below. But bug occurs regardless of settings.

![shot 1](https://user-images.githubusercontent.com/19936471/38899892-a047eb22-4256-11e8-933a-a3177c2c13bb.JPG)

**Comment by drodgers-ls** [comment]
I can confirm this bug.  Here's my report, which I was writing up until I found that there was a pre-existing issue.

Quite simply, the File / Quit menu selection in the Windows 10 Franz client (v5.0.0-beta.18) doesn't do anything.  Doesn't minimize the window, and certainly does not exit the Franz client, which is what I would expect.  More detail below.

"I wish I could quit you..."

### Expected Behavior
After clicking File, then Quit, the Franz client should terminate, its window should disappear, and it should no longer be running in Task Manager.  The behavior should be identical to when the main window control "X" is clicked when the "Keep Franz in background" option is de-selected.

### Current Behavior
Selecting File, then Quit, has no effect on the client.  Mouse-clicking on the menu is the only option, as there is no Alt-F shortcut for File, and no action shortcut for File / Quit.  Clicking window control "X" closes/minimizes the window, but Franz continues to run (blue bar under taskbar icon) if "Keep Franz in background" option is enabled (by default).  If the background option is de-selected, closing the window with "X" does quit Franz, and clicking the pinned taskbar icon re-starts the client (blue fill, Franz title, busy spinner, then services are restored).

Additionally, if I use Task Manager to kill Franz, it dies, but I get a pop-up Windows dialog box "Unable to terminate process (icon: red circle X) The operation could not be completed.  The operation is not valid for this process. [OK]"  If I have more than one service configured, I get multiple of these dialog boxes, one for each service configured.

### Screenshots (if appropriate):
See above.  Windows client runs, click File in menu bar, then click Quit, and observe that nothing happens.

### Possible Solution
A mild workaround is to de-select the "Keep Franz in background" option, and then click "X" only if I want to quit Franz, as opposed to minimize it.  But my habit is to click "X" assuming that it will continue to run.

### Steps to Reproduce (for bugs)
1. Install franz-setup-5.0.0-beta.18.exe.
2. Start Franz client.
3. Set up at least one service.  (I did not test behavior with zero services, but I wouldn't expect it to be different.  Issue exists with one or several services configured.)
4. Click File, then click Quit.  Observe that Franz client continues to run.

### Context
Simply need a way to quit Franz without de-selecting background option.

### Your Environment
* Franz Version used: 5.0.0-beta.18 (Windows x64)
* Operating System and version: Windows 10 Pro version 1709, fully patched.

**Comment by DigitalKeri** [comment]
Having the same issue - File > Quit has no effect, doesn't quit Franz, doesn't even quit the window.

As far as I can tell, the only way to exit Franz on Windows is to End task in Task Manager.

**Comment by requenaxii** [comment]
Same here, it's quite annoying, the only way to quit Franz is from the system tray; also could be great (as a MacOS user too) add a shortcut to quit on windows.
