### ISSUE TITLE
Franz for iOS

### ISSUE THREAD

**Issue by ghost** [meetfranz/franz#903]
Could you please consider implement this app for mobile platform. At least iOS?

**Comment by marcoslater** [comment]
This would be quite cool, but I feel that they're gonna have an issue doing it. Mainly because popular iOS chat apps aren't simply web-apps, so they can't just be ported into a different app that easily. You'd have to have it somehow containerise the apps within the app, or re-make them using API's, in either case thats a lot of engineering effort. 

It seems on desktop platforms you can get away with it because all the popular ones have web-versions of their application, because they expect users to use them in browsers the majority of the time. Thats all Frantz is at it's core from what I can see, a web browser primarily designed for chat, and, it's quite great at it!

**Comment by sweing** [comment]
Why wouldn’t it be possible to implement a browser app for chats in iOS like Franz? I can use safari to write messages in Facebook so why would there be a problem?
