### ISSUE TITLE
On Apple MacbokPro Franz uses the High Performance GPU

### ISSUE THREAD

**Issue by abpostelnicu** [meetfranz/franz#925]
OS: MacOS 10.13.4
Franz Version: 5.0.0-beta.18.903

When using Franz it uses the High Performance GPU
<img width="1044" alt="screen shot 2018-04-24 at 19 09 01" src="https://user-images.githubusercontent.com/11473159/39199783-0138061e-47f3-11e8-8d57-1870eae3d14a.png">

This is somehow strange and undesirable that a messaging platform should use this kind of resource. The effect is a drastic reduction in battery lifetime.

**Comment by abpostelnicu** [comment]
Maybe the problem lies here:

https://github.com/meetfranz/franz/blob/master/src/config.js#L24

**Comment by Heink** [comment]
Mmm, just instaleld Franz (and only a few accounts) and I'm seeing extreme CPU usage on my macBook and it doesn't seem to 'settle down' either.
![screencap_ 2018-04-27 at 10 26 54](https://user-images.githubusercontent.com/1921058/39355652-abde439e-4a05-11e8-81dd-a48e7bf3544c.png)

I'll leave it runnign for a bit (again) to see if switching the GPu off will make it go less CPU hungry (still at 46% CPU at this time) but I guess it won't.
Shame, promissing app, but this won't do.

**Comment by Heink** [comment]
Nope, runnign in between 25% and 85% all the time.
That is too much for thsi type of app.
![zzscreencap_](https://user-images.githubusercontent.com/1921058/39356165-35bbeaca-4a07-11e8-8999-cb70dcb01ff0.png)

**Comment by ayush-patel** [comment]
Bump. Still always uses the external GPU.
Franz: 5.0.0-beta.18.903

**Comment by SolidTerre** [comment]
Just disable GPU acceleration in Franz parameters...
![image](https://user-images.githubusercontent.com/8171049/41279020-a685fae6-6e2b-11e8-9a36-2788286c2ca1.png)

**Comment by Heink** [comment]
@SolidTerre I had tried that but that made no difference in my case.
Even then it still uses upward of 30% CPU at all times.

**Comment by gres147679** [comment]
Bump
@SolidTerre I've also tried disabling GPU acceleration, but it doesn't improve the issue at all. 
I see it consuming ~30% CPU at all times, and after leaving my laptop sleeping for ~11 hours, I see an average energy impact on the MacOS Activity Monitor of ~30, which brought my battery from 100% to ~70%
I can help folks debug this by providing more data. For instance, I noticed not all sub-processes consume CPU/energy. I tried looking at the open files and ports for each, but couldn't see anything that'd point out to a specific service (currently I have telegram, whatsapp, FB messenger, Slack, Gmail, Google Calendar, Google Keep, and Todoist)
Would a [process sample](https://support.omnigroup.com/sample-osx/) be useful, for instance? 

In the short-term, I'll probably keep Franz closed while I'm not using it. In the long-term, this may mean I stop using it altogether :/

**Comment by gres147679** [comment]
Huh, found [this related issue](https://github.com/meetfranz/franz/issues/24), tried disabling FB Messenger, and CPU is now ~1%. Maybe that's the root cause?
Can others try this out?

**Comment by fluffypony** [comment]
I'm on Franz 5.0.0.1136, and I'm not using FB Messenger. Franz absolutely kills my discrete GPU, and runs my CPU at ~40% most of the time. You can see in the graphs below I was running Franz, I quit and did a bunch of normal things that GPU acceleration (eg. Safari) and then opened Franz again.

GPU graph:

<img width="320" alt="Screenshot 2019-03-11 at 3 48 08 PM" src="https://user-images.githubusercontent.com/1944293/54128770-746fd980-4415-11e9-99f9-e6942273173f.png">

CPU graph:

<img width="306" alt="Screenshot 2019-03-11 at 3 48 22 PM" src="https://user-images.githubusercontent.com/1944293/54128771-746fd980-4415-11e9-9647-f9852b0f21cf.png">

I've tried disabling the GPU acceleration but then performance is absolutely terrible and entirely unusable. I can go and disable services one by one and see what the culprit is, if it'll help diagnose this.

**Comment by arvenil** [comment]
Related https://github.com/meetfranz/franz/issues/117
