### ISSUE TITLE
No icon for community-theme ubuntu 18.04

### ISSUE THREAD

**Issue by romainp89** [meetfranz/franz#940]
Hello,

I realized that Franz's icon does not display with the theme community-themes of ubuntu 18.04. Is it your responsibility?

Cheers :)

**Comment by gniezen** [comment]
I'm also on Ubuntu 18.04 using the AppImage. While I'm not using community-themes, I can confirm that I haven't seen the Franz icon since I first installed it on 17.10. Updating to `beta.18` didn't work either. However, I've just found a workaround (from https://github.com/laurent22/joplin/issues/86) that works:

In `~/.local/share/applications`, edit `appimagekit-franz.desktop` and add the following line:
```
StartupWMClass=Franz
```

**Comment by paulozava** [comment]
I have the same problem, and the correction works on Ubuntu 18.10
