### ISSUE TITLE
Ability to copy to clipboard the current url

### ISSUE THREAD

**Issue by leandrogehlen** [meetfranz/franz#947]
When we are using some service like github it's necessary to copy and past current url.

### Expected Behavior
It's necessary to add feature that allows to copy to clipboard currente url

### Your Environment

* Version: 5.0.0-beta.18 - Release: 1.8.4 / win32 / x64
* Windows 10

**Comment by dtakamoto** [comment]
👍

**Comment by billybooth** [comment]
Please this.  I am using Franz primarily for Zendesk, and we often exchange Zendesk URLs in internal discussions.  Having to jump out to the ticket view to share a URL with other team members is rather frustrating.

**Comment by KyleAtDND** [comment]
I was just about to add this with the information below. Instead of adding it separately, I'm putting it here @adlk 

**Is your feature request related to a problem? Please describe.**
Sometimes, I need a direct URL of the page I'm on in Franz. For instance, I may need to follow-up by email, and just send a link to the conversation that I had with someone in that email. Currently, in order to get that link, I have to leave Franz, go to Chrome, open up the same messaging service, find the conversation, and copy the link.

**Describe the solution you'd like**
A similar, but different function to Chrome so that Franz:
- Normally doesn't show the URL
- When I hit ⌘L or go to the corresponding menu bar it, it opens up the URL bar and automatically highlights all the text
- The URL bar can be read-only, or maybe just limited to setting a URL of the same domain of the messaging service
- Then I can click ⌘C or "Copy" to copy the URL

**Describe alternatives you've considered**
I've written above what I currently do.

**Comment by oojacoboo** [comment]
This is such a critical feature.  This is much needed!

**Comment by squirrelboot** [comment]
It also shouldn't be hard to implement. We have a 'Go Back' option when right-clicking the page. 
Why can't we have 'copy current url' (current page you are on), and also 'copy link' for any URL you are clicking on within a page, which goes to another page.

**Comment by sammy88888888** [comment]
Any headway on this? Would be a great to see this put in
