### ISSUE TITLE
Google inbox

### ISSUE THREAD

**Issue by mintyPT** [meetfranz/franz#96]
Cannot add google inbox

Made a quick [video](https://youtu.be/r-JANUO6nQk)

**Comment by fabiovianadotcom** [comment]
Same issue here

**Comment by adlk** [comment]
I'm testing a fix right now. In the meantime you can add it manually.
1. Close Franz
2. Download the recipe: https://api.franzinfra.com/v1/recipes/download/gmailinbox
3. Extract archive
4. Rename folder to gmailinbox
5. Move folder to:
  - Mac: `~Library/Application Support/Franz/recipes/`
  - Windows: `%appdata%/Franz/recipes/`
6. Start Franz
7. Go to "Available Services" and add Inbox as you would expect it.

I hope to be able to deploy the fix in a few hours.

Also this issue is connected with #67

**Comment by fabiovianadotcom** [comment]
It's working, thanks 👍

**Comment by joel-travieso** [comment]
The temporary workaround is not working for me (Mac OS Sierra)

**Comment by hdkiller** [comment]
Same problem here.

**Comment by adlk** [comment]
The latest version (beta 11) should fix this issue. Can you please ping me if it's working for you so I'm able to close this issue?

**Comment by mintyPT** [comment]
After the update it worked as expected.
